/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.records;


import javax.annotation.Generated;

import org.jooq.impl.TableRecordImpl;

import provendordb.tables._DbClass;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class _DbClassRecord extends TableRecordImpl<_DbClassRecord> {

    private static final long serialVersionUID = 1320788239;

    /**
     * Setter for <code>_db_class.class_of</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setClassOf(Object value) {
        set(0, value);
    }

    /**
     * Getter for <code>_db_class.class_of</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getClassOf() {
        return (Object) get(0);
    }

    /**
     * Setter for <code>_db_class.class_name</code>.
     */
    public void setClassName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>_db_class.class_name</code>.
     */
    public String getClassName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>_db_class.class_type</code>.
     */
    public void setClassType(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>_db_class.class_type</code>.
     */
    public Integer getClassType() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>_db_class.is_system_class</code>.
     */
    public void setIsSystemClass(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>_db_class.is_system_class</code>.
     */
    public Integer getIsSystemClass() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>_db_class.owner</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setOwner(Object value) {
        set(4, value);
    }

    /**
     * Getter for <code>_db_class.owner</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getOwner() {
        return (Object) get(4);
    }

    /**
     * Setter for <code>_db_class.inst_attr_count</code>.
     */
    public void setInstAttrCount(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>_db_class.inst_attr_count</code>.
     */
    public Integer getInstAttrCount() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>_db_class.class_attr_count</code>.
     */
    public void setClassAttrCount(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>_db_class.class_attr_count</code>.
     */
    public Integer getClassAttrCount() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>_db_class.shared_attr_count</code>.
     */
    public void setSharedAttrCount(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>_db_class.shared_attr_count</code>.
     */
    public Integer getSharedAttrCount() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>_db_class.inst_meth_count</code>.
     */
    public void setInstMethCount(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>_db_class.inst_meth_count</code>.
     */
    public Integer getInstMethCount() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>_db_class.class_meth_count</code>.
     */
    public void setClassMethCount(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>_db_class.class_meth_count</code>.
     */
    public Integer getClassMethCount() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>_db_class.collation_id</code>.
     */
    public void setCollationId(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>_db_class.collation_id</code>.
     */
    public Integer getCollationId() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>_db_class.sub_classes</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setSubClasses(Object value) {
        set(11, value);
    }

    /**
     * Getter for <code>_db_class.sub_classes</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getSubClasses() {
        return (Object) get(11);
    }

    /**
     * Setter for <code>_db_class.super_classes</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setSuperClasses(Object value) {
        set(12, value);
    }

    /**
     * Getter for <code>_db_class.super_classes</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getSuperClasses() {
        return (Object) get(12);
    }

    /**
     * Setter for <code>_db_class.inst_attrs</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setInstAttrs(Object value) {
        set(13, value);
    }

    /**
     * Getter for <code>_db_class.inst_attrs</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getInstAttrs() {
        return (Object) get(13);
    }

    /**
     * Setter for <code>_db_class.class_attrs</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setClassAttrs(Object value) {
        set(14, value);
    }

    /**
     * Getter for <code>_db_class.class_attrs</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getClassAttrs() {
        return (Object) get(14);
    }

    /**
     * Setter for <code>_db_class.shared_attrs</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setSharedAttrs(Object value) {
        set(15, value);
    }

    /**
     * Getter for <code>_db_class.shared_attrs</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getSharedAttrs() {
        return (Object) get(15);
    }

    /**
     * Setter for <code>_db_class.inst_meths</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setInstMeths(Object value) {
        set(16, value);
    }

    /**
     * Getter for <code>_db_class.inst_meths</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getInstMeths() {
        return (Object) get(16);
    }

    /**
     * Setter for <code>_db_class.class_meths</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setClassMeths(Object value) {
        set(17, value);
    }

    /**
     * Getter for <code>_db_class.class_meths</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getClassMeths() {
        return (Object) get(17);
    }

    /**
     * Setter for <code>_db_class.meth_files</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setMethFiles(Object value) {
        set(18, value);
    }

    /**
     * Getter for <code>_db_class.meth_files</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getMethFiles() {
        return (Object) get(18);
    }

    /**
     * Setter for <code>_db_class.query_specs</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setQuerySpecs(Object value) {
        set(19, value);
    }

    /**
     * Getter for <code>_db_class.query_specs</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getQuerySpecs() {
        return (Object) get(19);
    }

    /**
     * Setter for <code>_db_class.indexes</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setIndexes(Object value) {
        set(20, value);
    }

    /**
     * Getter for <code>_db_class.indexes</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getIndexes() {
        return (Object) get(20);
    }

    /**
     * Setter for <code>_db_class.comment</code>.
     */
    public void setComment(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>_db_class.comment</code>.
     */
    public String getComment() {
        return (String) get(21);
    }

    /**
     * Setter for <code>_db_class.partition</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setPartition(Object value) {
        set(22, value);
    }

    /**
     * Getter for <code>_db_class.partition</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getPartition() {
        return (Object) get(22);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached _DbClassRecord
     */
    public _DbClassRecord() {
        super(_DbClass._DB_CLASS);
    }

    /**
     * Create a detached, initialised _DbClassRecord
     */
    public _DbClassRecord(Object classOf, String className, Integer classType, Integer isSystemClass, Object owner, Integer instAttrCount, Integer classAttrCount, Integer sharedAttrCount, Integer instMethCount, Integer classMethCount, Integer collationId, Object subClasses, Object superClasses, Object instAttrs, Object classAttrs, Object sharedAttrs, Object instMeths, Object classMeths, Object methFiles, Object querySpecs, Object indexes, String comment, Object partition) {
        super(_DbClass._DB_CLASS);

        set(0, classOf);
        set(1, className);
        set(2, classType);
        set(3, isSystemClass);
        set(4, owner);
        set(5, instAttrCount);
        set(6, classAttrCount);
        set(7, sharedAttrCount);
        set(8, instMethCount);
        set(9, classMethCount);
        set(10, collationId);
        set(11, subClasses);
        set(12, superClasses);
        set(13, instAttrs);
        set(14, classAttrs);
        set(15, sharedAttrs);
        set(16, instMeths);
        set(17, classMeths);
        set(18, methFiles);
        set(19, querySpecs);
        set(20, indexes);
        set(21, comment);
        set(22, partition);
    }
}
