/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.TableRecordImpl;

import provendordb.tables._DbDomain;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class _DbDomainRecord extends TableRecordImpl<_DbDomainRecord> implements Record9<Object, Integer, Integer, Integer, Object, Integer, Integer, Object, Object> {

    private static final long serialVersionUID = 1101969152;

    /**
     * Setter for <code>_db_domain.object_of</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setObjectOf(Object value) {
        set(0, value);
    }

    /**
     * Getter for <code>_db_domain.object_of</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getObjectOf() {
        return (Object) get(0);
    }

    /**
     * Setter for <code>_db_domain.data_type</code>.
     */
    public void setDataType(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>_db_domain.data_type</code>.
     */
    public Integer getDataType() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>_db_domain.prec</code>.
     */
    public void setPrec(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>_db_domain.prec</code>.
     */
    public Integer getPrec() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>_db_domain.scale</code>.
     */
    public void setScale(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>_db_domain.scale</code>.
     */
    public Integer getScale() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>_db_domain.class_of</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setClassOf(Object value) {
        set(4, value);
    }

    /**
     * Getter for <code>_db_domain.class_of</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getClassOf() {
        return (Object) get(4);
    }

    /**
     * Setter for <code>_db_domain.code_set</code>.
     */
    public void setCodeSet(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>_db_domain.code_set</code>.
     */
    public Integer getCodeSet() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>_db_domain.collation_id</code>.
     */
    public void setCollationId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>_db_domain.collation_id</code>.
     */
    public Integer getCollationId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>_db_domain.enumeration</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setEnumeration(Object value) {
        set(7, value);
    }

    /**
     * Getter for <code>_db_domain.enumeration</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getEnumeration() {
        return (Object) get(7);
    }

    /**
     * Setter for <code>_db_domain.set_domains</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setSetDomains(Object value) {
        set(8, value);
    }

    /**
     * Getter for <code>_db_domain.set_domains</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getSetDomains() {
        return (Object) get(8);
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Object, Integer, Integer, Integer, Object, Integer, Integer, Object, Object> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Object, Integer, Integer, Integer, Object, Integer, Integer, Object, Object> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Field<Object> field1() {
        return _DbDomain._DB_DOMAIN.OBJECT_OF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return _DbDomain._DB_DOMAIN.DATA_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return _DbDomain._DB_DOMAIN.PREC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return _DbDomain._DB_DOMAIN.SCALE;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Field<Object> field5() {
        return _DbDomain._DB_DOMAIN.CLASS_OF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return _DbDomain._DB_DOMAIN.CODE_SET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return _DbDomain._DB_DOMAIN.COLLATION_ID;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Field<Object> field8() {
        return _DbDomain._DB_DOMAIN.ENUMERATION;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Field<Object> field9() {
        return _DbDomain._DB_DOMAIN.SET_DOMAINS;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Object component1() {
        return getObjectOf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getDataType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getPrec();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getScale();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Object component5() {
        return getClassOf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getCodeSet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getCollationId();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Object component8() {
        return getEnumeration();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Object component9() {
        return getSetDomains();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Object value1() {
        return getObjectOf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getDataType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPrec();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getScale();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Object value5() {
        return getClassOf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getCodeSet();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getCollationId();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Object value8() {
        return getEnumeration();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Object value9() {
        return getSetDomains();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public _DbDomainRecord value1(Object value) {
        setObjectOf(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _DbDomainRecord value2(Integer value) {
        setDataType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _DbDomainRecord value3(Integer value) {
        setPrec(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _DbDomainRecord value4(Integer value) {
        setScale(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public _DbDomainRecord value5(Object value) {
        setClassOf(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _DbDomainRecord value6(Integer value) {
        setCodeSet(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _DbDomainRecord value7(Integer value) {
        setCollationId(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public _DbDomainRecord value8(Object value) {
        setEnumeration(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public _DbDomainRecord value9(Object value) {
        setSetDomains(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _DbDomainRecord values(Object value1, Integer value2, Integer value3, Integer value4, Object value5, Integer value6, Integer value7, Object value8, Object value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached _DbDomainRecord
     */
    public _DbDomainRecord() {
        super(_DbDomain._DB_DOMAIN);
    }

    /**
     * Create a detached, initialised _DbDomainRecord
     */
    public _DbDomainRecord(Object objectOf, Integer dataType, Integer prec, Integer scale, Object classOf, Integer codeSet, Integer collationId, Object enumeration, Object setDomains) {
        super(_DbDomain._DB_DOMAIN);

        set(0, objectOf);
        set(1, dataType);
        set(2, prec);
        set(3, scale);
        set(4, classOf);
        set(5, codeSet);
        set(6, collationId);
        set(7, enumeration);
        set(8, setDomains);
    }
}
