/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;

import provendordb.tables._DbIndexKey;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class _DbIndexKeyRecord extends TableRecordImpl<_DbIndexKeyRecord> implements Record6<Object, String, Integer, Integer, Integer, String> {

    private static final long serialVersionUID = -1459494190;

    /**
     * Setter for <code>_db_index_key.index_of</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setIndexOf(Object value) {
        set(0, value);
    }

    /**
     * Getter for <code>_db_index_key.index_of</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getIndexOf() {
        return (Object) get(0);
    }

    /**
     * Setter for <code>_db_index_key.key_attr_name</code>.
     */
    public void setKeyAttrName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>_db_index_key.key_attr_name</code>.
     */
    public String getKeyAttrName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>_db_index_key.key_order</code>.
     */
    public void setKeyOrder(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>_db_index_key.key_order</code>.
     */
    public Integer getKeyOrder() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>_db_index_key.asc_desc</code>.
     */
    public void setAscDesc(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>_db_index_key.asc_desc</code>.
     */
    public Integer getAscDesc() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>_db_index_key.key_prefix_length</code>.
     */
    public void setKeyPrefixLength(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>_db_index_key.key_prefix_length</code>.
     */
    public Integer getKeyPrefixLength() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>_db_index_key.func</code>.
     */
    public void setFunc(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>_db_index_key.func</code>.
     */
    public String getFunc() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Object, String, Integer, Integer, Integer, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Object, String, Integer, Integer, Integer, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Field<Object> field1() {
        return _DbIndexKey._DB_INDEX_KEY.INDEX_OF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return _DbIndexKey._DB_INDEX_KEY.KEY_ATTR_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return _DbIndexKey._DB_INDEX_KEY.KEY_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return _DbIndexKey._DB_INDEX_KEY.ASC_DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return _DbIndexKey._DB_INDEX_KEY.KEY_PREFIX_LENGTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return _DbIndexKey._DB_INDEX_KEY.FUNC;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Object component1() {
        return getIndexOf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getKeyAttrName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getKeyOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getAscDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getKeyPrefixLength();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getFunc();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Object value1() {
        return getIndexOf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getKeyAttrName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getKeyOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getAscDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getKeyPrefixLength();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getFunc();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public _DbIndexKeyRecord value1(Object value) {
        setIndexOf(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _DbIndexKeyRecord value2(String value) {
        setKeyAttrName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _DbIndexKeyRecord value3(Integer value) {
        setKeyOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _DbIndexKeyRecord value4(Integer value) {
        setAscDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _DbIndexKeyRecord value5(Integer value) {
        setKeyPrefixLength(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _DbIndexKeyRecord value6(String value) {
        setFunc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _DbIndexKeyRecord values(Object value1, String value2, Integer value3, Integer value4, Integer value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached _DbIndexKeyRecord
     */
    public _DbIndexKeyRecord() {
        super(_DbIndexKey._DB_INDEX_KEY);
    }

    /**
     * Create a detached, initialised _DbIndexKeyRecord
     */
    public _DbIndexKeyRecord(Object indexOf, String keyAttrName, Integer keyOrder, Integer ascDesc, Integer keyPrefixLength, String func) {
        super(_DbIndexKey._DB_INDEX_KEY);

        set(0, indexOf);
        set(1, keyAttrName);
        set(2, keyOrder);
        set(3, ascDesc);
        set(4, keyPrefixLength);
        set(5, func);
    }
}
