/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;

import provendordb.tables._DbMethArg;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class _DbMethArgRecord extends TableRecordImpl<_DbMethArgRecord> implements Record4<Object, Integer, Integer, Object> {

    private static final long serialVersionUID = 1474630159;

    /**
     * Setter for <code>_db_meth_arg.meth_sig_of</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setMethSigOf(Object value) {
        set(0, value);
    }

    /**
     * Getter for <code>_db_meth_arg.meth_sig_of</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getMethSigOf() {
        return (Object) get(0);
    }

    /**
     * Setter for <code>_db_meth_arg.data_type</code>.
     */
    public void setDataType(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>_db_meth_arg.data_type</code>.
     */
    public Integer getDataType() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>_db_meth_arg.index_of</code>.
     */
    public void setIndexOf(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>_db_meth_arg.index_of</code>.
     */
    public Integer getIndexOf() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>_db_meth_arg.domains</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setDomains(Object value) {
        set(3, value);
    }

    /**
     * Getter for <code>_db_meth_arg.domains</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getDomains() {
        return (Object) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Object, Integer, Integer, Object> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Object, Integer, Integer, Object> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Field<Object> field1() {
        return _DbMethArg._DB_METH_ARG.METH_SIG_OF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return _DbMethArg._DB_METH_ARG.DATA_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return _DbMethArg._DB_METH_ARG.INDEX_OF;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Field<Object> field4() {
        return _DbMethArg._DB_METH_ARG.DOMAINS;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Object component1() {
        return getMethSigOf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getDataType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getIndexOf();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Object component4() {
        return getDomains();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Object value1() {
        return getMethSigOf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getDataType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getIndexOf();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Object value4() {
        return getDomains();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public _DbMethArgRecord value1(Object value) {
        setMethSigOf(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _DbMethArgRecord value2(Integer value) {
        setDataType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _DbMethArgRecord value3(Integer value) {
        setIndexOf(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public _DbMethArgRecord value4(Object value) {
        setDomains(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _DbMethArgRecord values(Object value1, Integer value2, Integer value3, Object value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached _DbMethArgRecord
     */
    public _DbMethArgRecord() {
        super(_DbMethArg._DB_METH_ARG);
    }

    /**
     * Create a detached, initialised _DbMethArgRecord
     */
    public _DbMethArgRecord(Object methSigOf, Integer dataType, Integer indexOf, Object domains) {
        super(_DbMethArg._DB_METH_ARG);

        set(0, methSigOf);
        set(1, dataType);
        set(2, indexOf);
        set(3, domains);
    }
}
