/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;

import provendordb.tables._DbQuerySpec;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class _DbQuerySpecRecord extends TableRecordImpl<_DbQuerySpecRecord> implements Record2<Object, String> {

    private static final long serialVersionUID = -1685747756;

    /**
     * Setter for <code>_db_query_spec.class_of</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setClassOf(Object value) {
        set(0, value);
    }

    /**
     * Getter for <code>_db_query_spec.class_of</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getClassOf() {
        return (Object) get(0);
    }

    /**
     * Setter for <code>_db_query_spec.spec</code>.
     */
    public void setSpec(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>_db_query_spec.spec</code>.
     */
    public String getSpec() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Object, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Object, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Field<Object> field1() {
        return _DbQuerySpec._DB_QUERY_SPEC.CLASS_OF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return _DbQuerySpec._DB_QUERY_SPEC.SPEC;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Object component1() {
        return getClassOf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSpec();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Object value1() {
        return getClassOf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSpec();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public _DbQuerySpecRecord value1(Object value) {
        setClassOf(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _DbQuerySpecRecord value2(String value) {
        setSpec(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _DbQuerySpecRecord values(Object value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached _DbQuerySpecRecord
     */
    public _DbQuerySpecRecord() {
        super(_DbQuerySpec._DB_QUERY_SPEC);
    }

    /**
     * Create a detached, initialised _DbQuerySpecRecord
     */
    public _DbQuerySpecRecord(Object classOf, String spec) {
        super(_DbQuerySpec._DB_QUERY_SPEC);

        set(0, classOf);
        set(1, spec);
    }
}
