/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.records;


import javax.annotation.Generated;

import org.jooq.impl.TableRecordImpl;

import provendordb.tables.DbAuthorizations;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbAuthorizationsRecord extends TableRecordImpl<DbAuthorizationsRecord> {

    private static final long serialVersionUID = 1311718440;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DbAuthorizationsRecord
     */
    public DbAuthorizationsRecord() {
        super(DbAuthorizations.DB_AUTHORIZATIONS);
    }
}
