/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;

import provendordb.tables.DbCharset;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbCharsetRecord extends TableRecordImpl<DbCharsetRecord> implements Record4<Integer, String, String, Integer> {

    private static final long serialVersionUID = 604574799;

    /**
     * Setter for <code>db_charset.charset_id</code>.
     */
    public void setCharsetId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>db_charset.charset_id</code>.
     */
    public Integer getCharsetId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>db_charset.charset_name</code>.
     */
    public void setCharsetName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>db_charset.charset_name</code>.
     */
    public String getCharsetName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>db_charset.default_collation</code>.
     */
    public void setDefaultCollation(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>db_charset.default_collation</code>.
     */
    public String getDefaultCollation() {
        return (String) get(2);
    }

    /**
     * Setter for <code>db_charset.char_size</code>.
     */
    public void setCharSize(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>db_charset.char_size</code>.
     */
    public Integer getCharSize() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DbCharset.DB_CHARSET.CHARSET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DbCharset.DB_CHARSET.CHARSET_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DbCharset.DB_CHARSET.DEFAULT_COLLATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return DbCharset.DB_CHARSET.CHAR_SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getCharsetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCharsetName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDefaultCollation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getCharSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCharsetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCharsetName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDefaultCollation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCharSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbCharsetRecord value1(Integer value) {
        setCharsetId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbCharsetRecord value2(String value) {
        setCharsetName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbCharsetRecord value3(String value) {
        setDefaultCollation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbCharsetRecord value4(Integer value) {
        setCharSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbCharsetRecord values(Integer value1, String value2, String value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DbCharsetRecord
     */
    public DbCharsetRecord() {
        super(DbCharset.DB_CHARSET);
    }

    /**
     * Create a detached, initialised DbCharsetRecord
     */
    public DbCharsetRecord(Integer charsetId, String charsetName, String defaultCollation, Integer charSize) {
        super(DbCharset.DB_CHARSET);

        set(0, charsetId);
        set(1, charsetName);
        set(2, defaultCollation);
        set(3, charSize);
    }
}
