/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.TableRecordImpl;

import provendordb.tables.DbIndexKey;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbIndexKeyRecord extends TableRecordImpl<DbIndexKeyRecord> implements Record7<String, String, String, Integer, String, Integer, String> {

    private static final long serialVersionUID = -1354313017;

    /**
     * Setter for <code>db_index_key.index_name</code>.
     */
    public void setIndexName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>db_index_key.index_name</code>.
     */
    public String getIndexName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>db_index_key.class_name</code>.
     */
    public void setClassName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>db_index_key.class_name</code>.
     */
    public String getClassName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>db_index_key.key_attr_name</code>.
     */
    public void setKeyAttrName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>db_index_key.key_attr_name</code>.
     */
    public String getKeyAttrName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>db_index_key.key_order</code>.
     */
    public void setKeyOrder(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>db_index_key.key_order</code>.
     */
    public Integer getKeyOrder() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>db_index_key.asc_desc</code>.
     */
    public void setAscDesc(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>db_index_key.asc_desc</code>.
     */
    public String getAscDesc() {
        return (String) get(4);
    }

    /**
     * Setter for <code>db_index_key.key_prefix_length</code>.
     */
    public void setKeyPrefixLength(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>db_index_key.key_prefix_length</code>.
     */
    public Integer getKeyPrefixLength() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>db_index_key.func</code>.
     */
    public void setFunc(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>db_index_key.func</code>.
     */
    public String getFunc() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, Integer, String, Integer, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, String, Integer, String, Integer, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return DbIndexKey.DB_INDEX_KEY.INDEX_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DbIndexKey.DB_INDEX_KEY.CLASS_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DbIndexKey.DB_INDEX_KEY.KEY_ATTR_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return DbIndexKey.DB_INDEX_KEY.KEY_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return DbIndexKey.DB_INDEX_KEY.ASC_DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return DbIndexKey.DB_INDEX_KEY.KEY_PREFIX_LENGTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return DbIndexKey.DB_INDEX_KEY.FUNC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getIndexName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getClassName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getKeyAttrName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getKeyOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getAscDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getKeyPrefixLength();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getFunc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getIndexName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getClassName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getKeyAttrName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getKeyOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getAscDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getKeyPrefixLength();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getFunc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbIndexKeyRecord value1(String value) {
        setIndexName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbIndexKeyRecord value2(String value) {
        setClassName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbIndexKeyRecord value3(String value) {
        setKeyAttrName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbIndexKeyRecord value4(Integer value) {
        setKeyOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbIndexKeyRecord value5(String value) {
        setAscDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbIndexKeyRecord value6(Integer value) {
        setKeyPrefixLength(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbIndexKeyRecord value7(String value) {
        setFunc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbIndexKeyRecord values(String value1, String value2, String value3, Integer value4, String value5, Integer value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DbIndexKeyRecord
     */
    public DbIndexKeyRecord() {
        super(DbIndexKey.DB_INDEX_KEY);
    }

    /**
     * Create a detached, initialised DbIndexKeyRecord
     */
    public DbIndexKeyRecord(String indexName, String className, String keyAttrName, Integer keyOrder, String ascDesc, Integer keyPrefixLength, String func) {
        super(DbIndexKey.DB_INDEX_KEY);

        set(0, indexName);
        set(1, className);
        set(2, keyAttrName);
        set(3, keyOrder);
        set(4, ascDesc);
        set(5, keyPrefixLength);
        set(6, func);
    }
}
