/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;

import provendordb.tables.DbMethod;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbMethodRecord extends TableRecordImpl<DbMethodRecord> implements Record6<String, String, String, String, String, String> {

    private static final long serialVersionUID = -2140996739;

    /**
     * Setter for <code>db_method.meth_name</code>.
     */
    public void setMethName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>db_method.meth_name</code>.
     */
    public String getMethName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>db_method.class_name</code>.
     */
    public void setClassName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>db_method.class_name</code>.
     */
    public String getClassName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>db_method.meth_type</code>.
     */
    public void setMethType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>db_method.meth_type</code>.
     */
    public String getMethType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>db_method.from_class_name</code>.
     */
    public void setFromClassName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>db_method.from_class_name</code>.
     */
    public String getFromClassName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>db_method.from_meth_name</code>.
     */
    public void setFromMethName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>db_method.from_meth_name</code>.
     */
    public String getFromMethName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>db_method.func_name</code>.
     */
    public void setFuncName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>db_method.func_name</code>.
     */
    public String getFuncName() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return DbMethod.DB_METHOD.METH_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DbMethod.DB_METHOD.CLASS_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DbMethod.DB_METHOD.METH_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return DbMethod.DB_METHOD.FROM_CLASS_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return DbMethod.DB_METHOD.FROM_METH_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return DbMethod.DB_METHOD.FUNC_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getMethName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getClassName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getMethType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getFromClassName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getFromMethName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getFuncName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getMethName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getClassName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMethType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getFromClassName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getFromMethName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getFuncName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbMethodRecord value1(String value) {
        setMethName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbMethodRecord value2(String value) {
        setClassName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbMethodRecord value3(String value) {
        setMethType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbMethodRecord value4(String value) {
        setFromClassName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbMethodRecord value5(String value) {
        setFromMethName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbMethodRecord value6(String value) {
        setFuncName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbMethodRecord values(String value1, String value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DbMethodRecord
     */
    public DbMethodRecord() {
        super(DbMethod.DB_METHOD);
    }

    /**
     * Create a detached, initialised DbMethodRecord
     */
    public DbMethodRecord(String methName, String className, String methType, String fromClassName, String fromMethName, String funcName) {
        super(DbMethod.DB_METHOD);

        set(0, methName);
        set(1, className);
        set(2, methType);
        set(3, fromClassName);
        set(4, fromMethName);
        set(5, funcName);
    }
}
