/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;

import provendordb.tables.DbStoredProcedureArgs;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbStoredProcedureArgsRecord extends TableRecordImpl<DbStoredProcedureArgsRecord> implements Record6<String, Integer, String, String, String, String> {

    private static final long serialVersionUID = 33489601;

    /**
     * Setter for <code>db_stored_procedure_args.sp_name</code>.
     */
    public void setSpName(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>db_stored_procedure_args.sp_name</code>.
     */
    public String getSpName() {
        return (String) get(0);
    }

    /**
     * Setter for <code>db_stored_procedure_args.index_of</code>.
     */
    public void setIndexOf(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>db_stored_procedure_args.index_of</code>.
     */
    public Integer getIndexOf() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>db_stored_procedure_args.arg_name</code>.
     */
    public void setArgName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>db_stored_procedure_args.arg_name</code>.
     */
    public String getArgName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>db_stored_procedure_args.data_type</code>.
     */
    public void setDataType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>db_stored_procedure_args.data_type</code>.
     */
    public String getDataType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>db_stored_procedure_args.mode</code>.
     */
    public void setMode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>db_stored_procedure_args.mode</code>.
     */
    public String getMode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>db_stored_procedure_args.comment</code>.
     */
    public void setComment(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>db_stored_procedure_args.comment</code>.
     */
    public String getComment() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, Integer, String, String, String, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, Integer, String, String, String, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return DbStoredProcedureArgs.DB_STORED_PROCEDURE_ARGS.SP_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return DbStoredProcedureArgs.DB_STORED_PROCEDURE_ARGS.INDEX_OF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return DbStoredProcedureArgs.DB_STORED_PROCEDURE_ARGS.ARG_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return DbStoredProcedureArgs.DB_STORED_PROCEDURE_ARGS.DATA_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return DbStoredProcedureArgs.DB_STORED_PROCEDURE_ARGS.MODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return DbStoredProcedureArgs.DB_STORED_PROCEDURE_ARGS.COMMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getSpName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getIndexOf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getArgName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDataType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getSpName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getIndexOf();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getArgName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDataType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbStoredProcedureArgsRecord value1(String value) {
        setSpName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbStoredProcedureArgsRecord value2(Integer value) {
        setIndexOf(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbStoredProcedureArgsRecord value3(String value) {
        setArgName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbStoredProcedureArgsRecord value4(String value) {
        setDataType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbStoredProcedureArgsRecord value5(String value) {
        setMode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbStoredProcedureArgsRecord value6(String value) {
        setComment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbStoredProcedureArgsRecord values(String value1, Integer value2, String value3, String value4, String value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DbStoredProcedureArgsRecord
     */
    public DbStoredProcedureArgsRecord() {
        super(DbStoredProcedureArgs.DB_STORED_PROCEDURE_ARGS);
    }

    /**
     * Create a detached, initialised DbStoredProcedureArgsRecord
     */
    public DbStoredProcedureArgsRecord(String spName, Integer indexOf, String argName, String dataType, String mode, String comment) {
        super(DbStoredProcedureArgs.DB_STORED_PROCEDURE_ARGS);

        set(0, spName);
        set(1, indexOf);
        set(2, argName);
        set(3, dataType);
        set(4, mode);
        set(5, comment);
    }
}
