/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.TableRecordImpl;

import provendordb.tables.DbTrigger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbTriggerRecord extends TableRecordImpl<DbTriggerRecord> implements Record15<Object, String, Integer, Double, Integer, Object, String, Integer, Integer, String, Integer, Integer, String, Integer, String> {

    private static final long serialVersionUID = 559127611;

    /**
     * Setter for <code>db_trigger.owner</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setOwner(Object value) {
        set(0, value);
    }

    /**
     * Getter for <code>db_trigger.owner</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getOwner() {
        return (Object) get(0);
    }

    /**
     * Setter for <code>db_trigger.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>db_trigger.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>db_trigger.status</code>.
     */
    public void setStatus(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>db_trigger.status</code>.
     */
    public Integer getStatus() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>db_trigger.priority</code>.
     */
    public void setPriority(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>db_trigger.priority</code>.
     */
    public Double getPriority() {
        return (Double) get(3);
    }

    /**
     * Setter for <code>db_trigger.event</code>.
     */
    public void setEvent(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>db_trigger.event</code>.
     */
    public Integer getEvent() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>db_trigger.target_class</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setTargetClass(Object value) {
        set(5, value);
    }

    /**
     * Getter for <code>db_trigger.target_class</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getTargetClass() {
        return (Object) get(5);
    }

    /**
     * Setter for <code>db_trigger.target_attribute</code>.
     */
    public void setTargetAttribute(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>db_trigger.target_attribute</code>.
     */
    public String getTargetAttribute() {
        return (String) get(6);
    }

    /**
     * Setter for <code>db_trigger.target_class_attribute</code>.
     */
    public void setTargetClassAttribute(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>db_trigger.target_class_attribute</code>.
     */
    public Integer getTargetClassAttribute() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>db_trigger.condition_type</code>.
     */
    public void setConditionType(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>db_trigger.condition_type</code>.
     */
    public Integer getConditionType() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>db_trigger.condition</code>.
     */
    public void setCondition(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>db_trigger.condition</code>.
     */
    public String getCondition() {
        return (String) get(9);
    }

    /**
     * Setter for <code>db_trigger.condition_time</code>.
     */
    public void setConditionTime(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>db_trigger.condition_time</code>.
     */
    public Integer getConditionTime() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>db_trigger.action_type</code>.
     */
    public void setActionType(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>db_trigger.action_type</code>.
     */
    public Integer getActionType() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>db_trigger.action_definition</code>.
     */
    public void setActionDefinition(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>db_trigger.action_definition</code>.
     */
    public String getActionDefinition() {
        return (String) get(12);
    }

    /**
     * Setter for <code>db_trigger.action_time</code>.
     */
    public void setActionTime(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>db_trigger.action_time</code>.
     */
    public Integer getActionTime() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>db_trigger.comment</code>.
     */
    public void setComment(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>db_trigger.comment</code>.
     */
    public String getComment() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Object, String, Integer, Double, Integer, Object, String, Integer, Integer, String, Integer, Integer, String, Integer, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Object, String, Integer, Double, Integer, Object, String, Integer, Integer, String, Integer, Integer, String, Integer, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Field<Object> field1() {
        return DbTrigger.DB_TRIGGER.OWNER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DbTrigger.DB_TRIGGER.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return DbTrigger.DB_TRIGGER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return DbTrigger.DB_TRIGGER.PRIORITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return DbTrigger.DB_TRIGGER.EVENT;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Field<Object> field6() {
        return DbTrigger.DB_TRIGGER.TARGET_CLASS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return DbTrigger.DB_TRIGGER.TARGET_ATTRIBUTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return DbTrigger.DB_TRIGGER.TARGET_CLASS_ATTRIBUTE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return DbTrigger.DB_TRIGGER.CONDITION_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return DbTrigger.DB_TRIGGER.CONDITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field11() {
        return DbTrigger.DB_TRIGGER.CONDITION_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return DbTrigger.DB_TRIGGER.ACTION_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return DbTrigger.DB_TRIGGER.ACTION_DEFINITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return DbTrigger.DB_TRIGGER.ACTION_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return DbTrigger.DB_TRIGGER.COMMENT;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Object component1() {
        return getOwner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component4() {
        return getPriority();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getEvent();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Object component6() {
        return getTargetClass();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getTargetAttribute();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getTargetClassAttribute();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getConditionType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getCondition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component11() {
        return getConditionTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component12() {
        return getActionType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getActionDefinition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component14() {
        return getActionTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getComment();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Object value1() {
        return getOwner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getPriority();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getEvent();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Object value6() {
        return getTargetClass();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getTargetAttribute();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getTargetClassAttribute();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getConditionType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCondition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value11() {
        return getConditionTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getActionType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getActionDefinition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getActionTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getComment();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public DbTriggerRecord value1(Object value) {
        setOwner(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbTriggerRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbTriggerRecord value3(Integer value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbTriggerRecord value4(Double value) {
        setPriority(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbTriggerRecord value5(Integer value) {
        setEvent(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public DbTriggerRecord value6(Object value) {
        setTargetClass(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbTriggerRecord value7(String value) {
        setTargetAttribute(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbTriggerRecord value8(Integer value) {
        setTargetClassAttribute(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbTriggerRecord value9(Integer value) {
        setConditionType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbTriggerRecord value10(String value) {
        setCondition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbTriggerRecord value11(Integer value) {
        setConditionTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbTriggerRecord value12(Integer value) {
        setActionType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbTriggerRecord value13(String value) {
        setActionDefinition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbTriggerRecord value14(Integer value) {
        setActionTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbTriggerRecord value15(String value) {
        setComment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbTriggerRecord values(Object value1, String value2, Integer value3, Double value4, Integer value5, Object value6, String value7, Integer value8, Integer value9, String value10, Integer value11, Integer value12, String value13, Integer value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DbTriggerRecord
     */
    public DbTriggerRecord() {
        super(DbTrigger.DB_TRIGGER);
    }

    /**
     * Create a detached, initialised DbTriggerRecord
     */
    public DbTriggerRecord(Object owner, String name, Integer status, Double priority, Integer event, Object targetClass, String targetAttribute, Integer targetClassAttribute, Integer conditionType, String condition, Integer conditionTime, Integer actionType, String actionDefinition, Integer actionTime, String comment) {
        super(DbTrigger.DB_TRIGGER);

        set(0, owner);
        set(1, name);
        set(2, status);
        set(3, priority);
        set(4, event);
        set(5, targetClass);
        set(6, targetAttribute);
        set(7, targetClassAttribute);
        set(8, conditionType);
        set(9, condition);
        set(10, conditionTime);
        set(11, actionType);
        set(12, actionDefinition);
        set(13, actionTime);
        set(14, comment);
    }
}
