/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import provendordb.tables.Provinfoitem;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProvinfoitemRecord extends UpdatableRecordImpl<ProvinfoitemRecord> implements Record5<String, String, String, String, String> {

    private static final long serialVersionUID = 136573946;

    /**
     * Setter for <code>provinfoitem.provinfoitemid</code>.
     */
    public void setProvinfoitemid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>provinfoitem.provinfoitemid</code>.
     */
    public String getProvinfoitemid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>provinfoitem.provinfoitemname</code>.
     */
    public void setProvinfoitemname(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>provinfoitem.provinfoitemname</code>.
     */
    public String getProvinfoitemname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>provinfoitem.provinfoitemdesc</code>.
     */
    public void setProvinfoitemdesc(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>provinfoitem.provinfoitemdesc</code>.
     */
    public String getProvinfoitemdesc() {
        return (String) get(2);
    }

    /**
     * Setter for <code>provinfoitem.provinfoitemquantity</code>.
     */
    public void setProvinfoitemquantity(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>provinfoitem.provinfoitemquantity</code>.
     */
    public String getProvinfoitemquantity() {
        return (String) get(3);
    }

    /**
     * Setter for <code>provinfoitem.provinfoitemexpiry</code>.
     */
    public void setProvinfoitemexpiry(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>provinfoitem.provinfoitemexpiry</code>.
     */
    public String getProvinfoitemexpiry() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Provinfoitem.PROVINFOITEM.PROVINFOITEMID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Provinfoitem.PROVINFOITEM.PROVINFOITEMNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Provinfoitem.PROVINFOITEM.PROVINFOITEMDESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Provinfoitem.PROVINFOITEM.PROVINFOITEMQUANTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Provinfoitem.PROVINFOITEM.PROVINFOITEMEXPIRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getProvinfoitemid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getProvinfoitemname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getProvinfoitemdesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getProvinfoitemquantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getProvinfoitemexpiry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getProvinfoitemid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProvinfoitemname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getProvinfoitemdesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getProvinfoitemquantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getProvinfoitemexpiry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvinfoitemRecord value1(String value) {
        setProvinfoitemid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvinfoitemRecord value2(String value) {
        setProvinfoitemname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvinfoitemRecord value3(String value) {
        setProvinfoitemdesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvinfoitemRecord value4(String value) {
        setProvinfoitemquantity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvinfoitemRecord value5(String value) {
        setProvinfoitemexpiry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvinfoitemRecord values(String value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProvinfoitemRecord
     */
    public ProvinfoitemRecord() {
        super(Provinfoitem.PROVINFOITEM);
    }

    /**
     * Create a detached, initialised ProvinfoitemRecord
     */
    public ProvinfoitemRecord(String provinfoitemid, String provinfoitemname, String provinfoitemdesc, String provinfoitemquantity, String provinfoitemexpiry) {
        super(Provinfoitem.PROVINFOITEM);

        set(0, provinfoitemid);
        set(1, provinfoitemname);
        set(2, provinfoitemdesc);
        set(3, provinfoitemquantity);
        set(4, provinfoitemexpiry);
    }
}
