/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;

import provendordb.tables.Provuser;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProvuserRecord extends UpdatableRecordImpl<ProvuserRecord> implements Record19<Integer, String, Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, Integer, Integer, Integer> {

    private static final long serialVersionUID = -519429628;

    /**
     * Setter for <code>provuser.provuserid</code>.
     */
    public void setProvuserid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>provuser.provuserid</code>.
     */
    public Integer getProvuserid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>provuser.provusername</code>.
     */
    public void setProvusername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>provuser.provusername</code>.
     */
    public String getProvusername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>provuser.provuseraadhar</code>.
     */
    public void setProvuseraadhar(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>provuser.provuseraadhar</code>.
     */
    public Integer getProvuseraadhar() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>provuser.provuserfirstname</code>.
     */
    public void setProvuserfirstname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>provuser.provuserfirstname</code>.
     */
    public String getProvuserfirstname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>provuser.provuserlastname</code>.
     */
    public void setProvuserlastname(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>provuser.provuserlastname</code>.
     */
    public String getProvuserlastname() {
        return (String) get(4);
    }

    /**
     * Setter for <code>provuser.provuserpassword</code>.
     */
    public void setProvuserpassword(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>provuser.provuserpassword</code>.
     */
    public String getProvuserpassword() {
        return (String) get(5);
    }

    /**
     * Setter for <code>provuser.provuseremail</code>.
     */
    public void setProvuseremail(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>provuser.provuseremail</code>.
     */
    public String getProvuseremail() {
        return (String) get(6);
    }

    /**
     * Setter for <code>provuser.provusermobile</code>.
     */
    public void setProvusermobile(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>provuser.provusermobile</code>.
     */
    public String getProvusermobile() {
        return (String) get(7);
    }

    /**
     * Setter for <code>provuser.provusermobile2</code>.
     */
    public void setProvusermobile2(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>provuser.provusermobile2</code>.
     */
    public String getProvusermobile2() {
        return (String) get(8);
    }

    /**
     * Setter for <code>provuser.provuseraddress</code>.
     */
    public void setProvuseraddress(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>provuser.provuseraddress</code>.
     */
    public String getProvuseraddress() {
        return (String) get(9);
    }

    /**
     * Setter for <code>provuser.provusercity</code>.
     */
    public void setProvusercity(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>provuser.provusercity</code>.
     */
    public String getProvusercity() {
        return (String) get(10);
    }

    /**
     * Setter for <code>provuser.provuserstate</code>.
     */
    public void setProvuserstate(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>provuser.provuserstate</code>.
     */
    public String getProvuserstate() {
        return (String) get(11);
    }

    /**
     * Setter for <code>provuser.provusercountry</code>.
     */
    public void setProvusercountry(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>provuser.provusercountry</code>.
     */
    public String getProvusercountry() {
        return (String) get(12);
    }

    /**
     * Setter for <code>provuser.provuserdivision</code>.
     */
    public void setProvuserdivision(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>provuser.provuserdivision</code>.
     */
    public String getProvuserdivision() {
        return (String) get(13);
    }

    /**
     * Setter for <code>provuser.provinterests</code>.
     */
    public void setProvinterests(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>provuser.provinterests</code>.
     */
    public String getProvinterests() {
        return (String) get(14);
    }

    /**
     * Setter for <code>provuser.provuserwishlist</code>.
     */
    public void setProvuserwishlist(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>provuser.provuserwishlist</code>.
     */
    public String getProvuserwishlist() {
        return (String) get(15);
    }

    /**
     * Setter for <code>provuser.provuserrole</code>.
     */
    public void setProvuserrole(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>provuser.provuserrole</code>.
     */
    public Integer getProvuserrole() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>provuser.provuseratings</code>.
     */
    public void setProvuseratings(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>provuser.provuseratings</code>.
     */
    public Integer getProvuseratings() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>provuser.provusernumber</code>.
     */
    public void setProvusernumber(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>provuser.provusernumber</code>.
     */
    public Integer getProvusernumber() {
        return (Integer) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row19<Integer, String, Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, Integer, Integer, Integer> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row19<Integer, String, Integer, String, String, String, String, String, String, String, String, String, String, String, String, String, Integer, Integer, Integer> valuesRow() {
        return (Row19) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Provuser.PROVUSER.PROVUSERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Provuser.PROVUSER.PROVUSERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Provuser.PROVUSER.PROVUSERAADHAR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Provuser.PROVUSER.PROVUSERFIRSTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Provuser.PROVUSER.PROVUSERLASTNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Provuser.PROVUSER.PROVUSERPASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Provuser.PROVUSER.PROVUSEREMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Provuser.PROVUSER.PROVUSERMOBILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Provuser.PROVUSER.PROVUSERMOBILE2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Provuser.PROVUSER.PROVUSERADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Provuser.PROVUSER.PROVUSERCITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Provuser.PROVUSER.PROVUSERSTATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Provuser.PROVUSER.PROVUSERCOUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Provuser.PROVUSER.PROVUSERDIVISION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Provuser.PROVUSER.PROVINTERESTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return Provuser.PROVUSER.PROVUSERWISHLIST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field17() {
        return Provuser.PROVUSER.PROVUSERROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field18() {
        return Provuser.PROVUSER.PROVUSERATINGS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field19() {
        return Provuser.PROVUSER.PROVUSERNUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getProvuserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getProvusername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getProvuseraadhar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getProvuserfirstname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getProvuserlastname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getProvuserpassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getProvuseremail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getProvusermobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getProvusermobile2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getProvuseraddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getProvusercity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getProvuserstate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getProvusercountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getProvuserdivision();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getProvinterests();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getProvuserwishlist();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component17() {
        return getProvuserrole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component18() {
        return getProvuseratings();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component19() {
        return getProvusernumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getProvuserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getProvusername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getProvuseraadhar();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getProvuserfirstname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getProvuserlastname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getProvuserpassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getProvuseremail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getProvusermobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getProvusermobile2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getProvuseraddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getProvusercity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getProvuserstate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getProvusercountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getProvuserdivision();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getProvinterests();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getProvuserwishlist();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value17() {
        return getProvuserrole();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value18() {
        return getProvuseratings();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value19() {
        return getProvusernumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvuserRecord value1(Integer value) {
        setProvuserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvuserRecord value2(String value) {
        setProvusername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvuserRecord value3(Integer value) {
        setProvuseraadhar(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvuserRecord value4(String value) {
        setProvuserfirstname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvuserRecord value5(String value) {
        setProvuserlastname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvuserRecord value6(String value) {
        setProvuserpassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvuserRecord value7(String value) {
        setProvuseremail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvuserRecord value8(String value) {
        setProvusermobile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvuserRecord value9(String value) {
        setProvusermobile2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvuserRecord value10(String value) {
        setProvuseraddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvuserRecord value11(String value) {
        setProvusercity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvuserRecord value12(String value) {
        setProvuserstate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvuserRecord value13(String value) {
        setProvusercountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvuserRecord value14(String value) {
        setProvuserdivision(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvuserRecord value15(String value) {
        setProvinterests(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvuserRecord value16(String value) {
        setProvuserwishlist(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvuserRecord value17(Integer value) {
        setProvuserrole(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvuserRecord value18(Integer value) {
        setProvuseratings(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvuserRecord value19(Integer value) {
        setProvusernumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvuserRecord values(Integer value1, String value2, Integer value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16, Integer value17, Integer value18, Integer value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProvuserRecord
     */
    public ProvuserRecord() {
        super(Provuser.PROVUSER);
    }

    /**
     * Create a detached, initialised ProvuserRecord
     */
    public ProvuserRecord(Integer provuserid, String provusername, Integer provuseraadhar, String provuserfirstname, String provuserlastname, String provuserpassword, String provuseremail, String provusermobile, String provusermobile2, String provuseraddress, String provusercity, String provuserstate, String provusercountry, String provuserdivision, String provinterests, String provuserwishlist, Integer provuserrole, Integer provuseratings, Integer provusernumber) {
        super(Provuser.PROVUSER);

        set(0, provuserid);
        set(1, provusername);
        set(2, provuseraadhar);
        set(3, provuserfirstname);
        set(4, provuserlastname);
        set(5, provuserpassword);
        set(6, provuseremail);
        set(7, provusermobile);
        set(8, provusermobile2);
        set(9, provuseraddress);
        set(10, provusercity);
        set(11, provuserstate);
        set(12, provusercountry);
        set(13, provuserdivision);
        set(14, provinterests);
        set(15, provuserwishlist);
        set(16, provuserrole);
        set(17, provuseratings);
        set(18, provusernumber);
    }
}
