/*
 * This file is generated by jOOQ.
*/
package provendordb;


import javax.annotation.Generated;

import provendordb.tables.DbAttrSetdomainElm;
import provendordb.tables.DbAttribute;
import provendordb.tables.DbAuth;
import provendordb.tables.DbAuthorization;
import provendordb.tables.DbAuthorizations;
import provendordb.tables.DbCharset;
import provendordb.tables.DbClass;
import provendordb.tables.DbCollation;
import provendordb.tables.DbDirectSuperClass;
import provendordb.tables.DbHaApplyInfo;
import provendordb.tables.DbIndex;
import provendordb.tables.DbIndexKey;
import provendordb.tables.DbMethArg;
import provendordb.tables.DbMethArgSetdomainElm;
import provendordb.tables.DbMethFile;
import provendordb.tables.DbMethod;
import provendordb.tables.DbPartition;
import provendordb.tables.DbPassword;
import provendordb.tables.DbRoot;
import provendordb.tables.DbSerial;
import provendordb.tables.DbStoredProcedure;
import provendordb.tables.DbStoredProcedureArgs;
import provendordb.tables.DbTrig;
import provendordb.tables.DbTrigger;
import provendordb.tables.DbUser;
import provendordb.tables.DbVclass;
import provendordb.tables.Provinfoitem;
import provendordb.tables.Provinfoitemgroup;
import provendordb.tables.Provinfoitemtype;
import provendordb.tables.Provitem;
import provendordb.tables.Provsalesinvoice;
import provendordb.tables.Provsalesorder;
import provendordb.tables.Provuser;
import provendordb.tables.Pvsalesorderitems;
import provendordb.tables._DbAttribute;
import provendordb.tables._DbAuth;
import provendordb.tables._DbCharset;
import provendordb.tables._DbClass;
import provendordb.tables._DbCollation;
import provendordb.tables._DbDataType;
import provendordb.tables._DbDomain;
import provendordb.tables._DbIndex;
import provendordb.tables._DbIndexKey;
import provendordb.tables._DbMethArg;
import provendordb.tables._DbMethFile;
import provendordb.tables._DbMethSig;
import provendordb.tables._DbMethod;
import provendordb.tables._DbPartition;
import provendordb.tables._DbQuerySpec;
import provendordb.tables._DbStoredProcedure;
import provendordb.tables._DbStoredProcedureArgs;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>_db_attribute</code>.
     */
    public static final _DbAttribute _DB_ATTRIBUTE = provendordb.tables._DbAttribute._DB_ATTRIBUTE;

    /**
     * The table <code>_db_auth</code>.
     */
    public static final _DbAuth _DB_AUTH = provendordb.tables._DbAuth._DB_AUTH;

    /**
     * The table <code>_db_charset</code>.
     */
    public static final _DbCharset _DB_CHARSET = provendordb.tables._DbCharset._DB_CHARSET;

    /**
     * The table <code>_db_class</code>.
     */
    public static final _DbClass _DB_CLASS = provendordb.tables._DbClass._DB_CLASS;

    /**
     * The table <code>_db_collation</code>.
     */
    public static final _DbCollation _DB_COLLATION = provendordb.tables._DbCollation._DB_COLLATION;

    /**
     * The table <code>_db_data_type</code>.
     */
    public static final _DbDataType _DB_DATA_TYPE = provendordb.tables._DbDataType._DB_DATA_TYPE;

    /**
     * The table <code>_db_domain</code>.
     */
    public static final _DbDomain _DB_DOMAIN = provendordb.tables._DbDomain._DB_DOMAIN;

    /**
     * The table <code>_db_index</code>.
     */
    public static final _DbIndex _DB_INDEX = provendordb.tables._DbIndex._DB_INDEX;

    /**
     * The table <code>_db_index_key</code>.
     */
    public static final _DbIndexKey _DB_INDEX_KEY = provendordb.tables._DbIndexKey._DB_INDEX_KEY;

    /**
     * The table <code>_db_meth_arg</code>.
     */
    public static final _DbMethArg _DB_METH_ARG = provendordb.tables._DbMethArg._DB_METH_ARG;

    /**
     * The table <code>_db_meth_file</code>.
     */
    public static final _DbMethFile _DB_METH_FILE = provendordb.tables._DbMethFile._DB_METH_FILE;

    /**
     * The table <code>_db_meth_sig</code>.
     */
    public static final _DbMethSig _DB_METH_SIG = provendordb.tables._DbMethSig._DB_METH_SIG;

    /**
     * The table <code>_db_method</code>.
     */
    public static final _DbMethod _DB_METHOD = provendordb.tables._DbMethod._DB_METHOD;

    /**
     * The table <code>_db_partition</code>.
     */
    public static final _DbPartition _DB_PARTITION = provendordb.tables._DbPartition._DB_PARTITION;

    /**
     * The table <code>_db_query_spec</code>.
     */
    public static final _DbQuerySpec _DB_QUERY_SPEC = provendordb.tables._DbQuerySpec._DB_QUERY_SPEC;

    /**
     * The table <code>_db_stored_procedure</code>.
     */
    public static final _DbStoredProcedure _DB_STORED_PROCEDURE = provendordb.tables._DbStoredProcedure._DB_STORED_PROCEDURE;

    /**
     * The table <code>_db_stored_procedure_args</code>.
     */
    public static final _DbStoredProcedureArgs _DB_STORED_PROCEDURE_ARGS = provendordb.tables._DbStoredProcedureArgs._DB_STORED_PROCEDURE_ARGS;

    /**
     * The table <code>db_attr_setdomain_elm</code>.
     */
    public static final DbAttrSetdomainElm DB_ATTR_SETDOMAIN_ELM = provendordb.tables.DbAttrSetdomainElm.DB_ATTR_SETDOMAIN_ELM;

    /**
     * The table <code>db_attribute</code>.
     */
    public static final DbAttribute DB_ATTRIBUTE = provendordb.tables.DbAttribute.DB_ATTRIBUTE;

    /**
     * The table <code>db_auth</code>.
     */
    public static final DbAuth DB_AUTH = provendordb.tables.DbAuth.DB_AUTH;

    /**
     * The table <code>db_authorization</code>.
     */
    public static final DbAuthorization DB_AUTHORIZATION = provendordb.tables.DbAuthorization.DB_AUTHORIZATION;

    /**
     * The table <code>db_authorizations</code>.
     */
    public static final DbAuthorizations DB_AUTHORIZATIONS = provendordb.tables.DbAuthorizations.DB_AUTHORIZATIONS;

    /**
     * The table <code>db_charset</code>.
     */
    public static final DbCharset DB_CHARSET = provendordb.tables.DbCharset.DB_CHARSET;

    /**
     * The table <code>db_class</code>.
     */
    public static final DbClass DB_CLASS = provendordb.tables.DbClass.DB_CLASS;

    /**
     * The table <code>db_collation</code>.
     */
    public static final DbCollation DB_COLLATION = provendordb.tables.DbCollation.DB_COLLATION;

    /**
     * The table <code>db_direct_super_class</code>.
     */
    public static final DbDirectSuperClass DB_DIRECT_SUPER_CLASS = provendordb.tables.DbDirectSuperClass.DB_DIRECT_SUPER_CLASS;

    /**
     * The table <code>db_ha_apply_info</code>.
     */
    public static final DbHaApplyInfo DB_HA_APPLY_INFO = provendordb.tables.DbHaApplyInfo.DB_HA_APPLY_INFO;

    /**
     * The table <code>db_index</code>.
     */
    public static final DbIndex DB_INDEX = provendordb.tables.DbIndex.DB_INDEX;

    /**
     * The table <code>db_index_key</code>.
     */
    public static final DbIndexKey DB_INDEX_KEY = provendordb.tables.DbIndexKey.DB_INDEX_KEY;

    /**
     * The table <code>db_meth_arg</code>.
     */
    public static final DbMethArg DB_METH_ARG = provendordb.tables.DbMethArg.DB_METH_ARG;

    /**
     * The table <code>db_meth_arg_setdomain_elm</code>.
     */
    public static final DbMethArgSetdomainElm DB_METH_ARG_SETDOMAIN_ELM = provendordb.tables.DbMethArgSetdomainElm.DB_METH_ARG_SETDOMAIN_ELM;

    /**
     * The table <code>db_meth_file</code>.
     */
    public static final DbMethFile DB_METH_FILE = provendordb.tables.DbMethFile.DB_METH_FILE;

    /**
     * The table <code>db_method</code>.
     */
    public static final DbMethod DB_METHOD = provendordb.tables.DbMethod.DB_METHOD;

    /**
     * The table <code>db_partition</code>.
     */
    public static final DbPartition DB_PARTITION = provendordb.tables.DbPartition.DB_PARTITION;

    /**
     * The table <code>db_password</code>.
     */
    public static final DbPassword DB_PASSWORD = provendordb.tables.DbPassword.DB_PASSWORD;

    /**
     * The table <code>db_root</code>.
     */
    public static final DbRoot DB_ROOT = provendordb.tables.DbRoot.DB_ROOT;

    /**
     * The table <code>db_serial</code>.
     */
    public static final DbSerial DB_SERIAL = provendordb.tables.DbSerial.DB_SERIAL;

    /**
     * The table <code>db_stored_procedure</code>.
     */
    public static final DbStoredProcedure DB_STORED_PROCEDURE = provendordb.tables.DbStoredProcedure.DB_STORED_PROCEDURE;

    /**
     * The table <code>db_stored_procedure_args</code>.
     */
    public static final DbStoredProcedureArgs DB_STORED_PROCEDURE_ARGS = provendordb.tables.DbStoredProcedureArgs.DB_STORED_PROCEDURE_ARGS;

    /**
     * The table <code>db_trig</code>.
     */
    public static final DbTrig DB_TRIG = provendordb.tables.DbTrig.DB_TRIG;

    /**
     * The table <code>db_trigger</code>.
     */
    public static final DbTrigger DB_TRIGGER = provendordb.tables.DbTrigger.DB_TRIGGER;

    /**
     * The table <code>db_user</code>.
     */
    public static final DbUser DB_USER = provendordb.tables.DbUser.DB_USER;

    /**
     * The table <code>db_vclass</code>.
     */
    public static final DbVclass DB_VCLASS = provendordb.tables.DbVclass.DB_VCLASS;

    /**
     * The table <code>provinfoitem</code>.
     */
    public static final Provinfoitem PROVINFOITEM = provendordb.tables.Provinfoitem.PROVINFOITEM;

    /**
     * The table <code>provinfoitemgroup</code>.
     */
    public static final Provinfoitemgroup PROVINFOITEMGROUP = provendordb.tables.Provinfoitemgroup.PROVINFOITEMGROUP;

    /**
     * The table <code>provinfoitemtype</code>.
     */
    public static final Provinfoitemtype PROVINFOITEMTYPE = provendordb.tables.Provinfoitemtype.PROVINFOITEMTYPE;

    /**
     * The table <code>provitem</code>.
     */
    public static final Provitem PROVITEM = provendordb.tables.Provitem.PROVITEM;

    /**
     * The table <code>provsalesinvoice</code>.
     */
    public static final Provsalesinvoice PROVSALESINVOICE = provendordb.tables.Provsalesinvoice.PROVSALESINVOICE;

    /**
     * The table <code>provsalesorder</code>.
     */
    public static final Provsalesorder PROVSALESORDER = provendordb.tables.Provsalesorder.PROVSALESORDER;

    /**
     * The table <code>provuser</code>.
     */
    public static final Provuser PROVUSER = provendordb.tables.Provuser.PROVUSER;

    /**
     * The table <code>pvsalesorderitems</code>.
     */
    public static final Pvsalesorderitems PVSALESORDERITEMS = provendordb.tables.Pvsalesorderitems.PVSALESORDERITEMS;
}
