/*
 * This file is generated by jOOQ.
*/
package provendordb.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import provendordb.DefaultSchema;
import provendordb.tables.records._DbAttributeRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class _DbAttribute extends TableImpl<_DbAttributeRecord> {

    private static final long serialVersionUID = -1091126106;

    /**
     * The reference instance of <code>_db_attribute</code>
     */
    public static final _DbAttribute _DB_ATTRIBUTE = new _DbAttribute();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<_DbAttributeRecord> getRecordType() {
        return _DbAttributeRecord.class;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public final TableField<_DbAttributeRecord, Object> CLASS_OF = createField("class_of", org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * The column <code>_db_attribute.attr_name</code>.
     */
    public final TableField<_DbAttributeRecord, String> ATTR_NAME = createField("attr_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>_db_attribute.attr_type</code>.
     */
    public final TableField<_DbAttributeRecord, Integer> ATTR_TYPE = createField("attr_type", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public final TableField<_DbAttributeRecord, Object> FROM_CLASS_OF = createField("from_class_of", org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * The column <code>_db_attribute.from_attr_name</code>.
     */
    public final TableField<_DbAttributeRecord, String> FROM_ATTR_NAME = createField("from_attr_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>_db_attribute.def_order</code>.
     */
    public final TableField<_DbAttributeRecord, Integer> DEF_ORDER = createField("def_order", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>_db_attribute.data_type</code>.
     */
    public final TableField<_DbAttributeRecord, Integer> DATA_TYPE = createField("data_type", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>_db_attribute.default_value</code>.
     */
    public final TableField<_DbAttributeRecord, String> DEFAULT_VALUE = createField("default_value", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public final TableField<_DbAttributeRecord, Object> DOMAINS = createField("domains", org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * The column <code>_db_attribute.is_nullable</code>.
     */
    public final TableField<_DbAttributeRecord, Integer> IS_NULLABLE = createField("is_nullable", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>_db_attribute.comment</code>.
     */
    public final TableField<_DbAttributeRecord, String> COMMENT = createField("comment", org.jooq.impl.SQLDataType.VARCHAR(1024), this, "");

    /**
     * Create a <code>_db_attribute</code> table reference
     */
    public _DbAttribute() {
        this(DSL.name("_db_attribute"), null);
    }

    /**
     * Create an aliased <code>_db_attribute</code> table reference
     */
    public _DbAttribute(String alias) {
        this(DSL.name(alias), _DB_ATTRIBUTE);
    }

    /**
     * Create an aliased <code>_db_attribute</code> table reference
     */
    public _DbAttribute(Name alias) {
        this(alias, _DB_ATTRIBUTE);
    }

    private _DbAttribute(Name alias, Table<_DbAttributeRecord> aliased) {
        this(alias, aliased, null);
    }

    private _DbAttribute(Name alias, Table<_DbAttributeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _DbAttribute as(String alias) {
        return new _DbAttribute(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _DbAttribute as(Name alias) {
        return new _DbAttribute(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public _DbAttribute rename(String name) {
        return new _DbAttribute(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public _DbAttribute rename(Name name) {
        return new _DbAttribute(name, null);
    }
}
