/*
 * This file is generated by jOOQ.
*/
package provendordb.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import provendordb.DefaultSchema;
import provendordb.tables.records._DbMethArgRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class _DbMethArg extends TableImpl<_DbMethArgRecord> {

    private static final long serialVersionUID = -547417398;

    /**
     * The reference instance of <code>_db_meth_arg</code>
     */
    public static final _DbMethArg _DB_METH_ARG = new _DbMethArg();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<_DbMethArgRecord> getRecordType() {
        return _DbMethArgRecord.class;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public final TableField<_DbMethArgRecord, Object> METH_SIG_OF = createField("meth_sig_of", org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * The column <code>_db_meth_arg.data_type</code>.
     */
    public final TableField<_DbMethArgRecord, Integer> DATA_TYPE = createField("data_type", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>_db_meth_arg.index_of</code>.
     */
    public final TableField<_DbMethArgRecord, Integer> INDEX_OF = createField("index_of", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public final TableField<_DbMethArgRecord, Object> DOMAINS = createField("domains", org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * Create a <code>_db_meth_arg</code> table reference
     */
    public _DbMethArg() {
        this(DSL.name("_db_meth_arg"), null);
    }

    /**
     * Create an aliased <code>_db_meth_arg</code> table reference
     */
    public _DbMethArg(String alias) {
        this(DSL.name(alias), _DB_METH_ARG);
    }

    /**
     * Create an aliased <code>_db_meth_arg</code> table reference
     */
    public _DbMethArg(Name alias) {
        this(alias, _DB_METH_ARG);
    }

    private _DbMethArg(Name alias, Table<_DbMethArgRecord> aliased) {
        this(alias, aliased, null);
    }

    private _DbMethArg(Name alias, Table<_DbMethArgRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _DbMethArg as(String alias) {
        return new _DbMethArg(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _DbMethArg as(Name alias) {
        return new _DbMethArg(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public _DbMethArg rename(String name) {
        return new _DbMethArg(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public _DbMethArg rename(Name name) {
        return new _DbMethArg(name, null);
    }
}
