/*
 * This file is generated by jOOQ.
*/
package provendordb.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import provendordb.DefaultSchema;
import provendordb.tables.records._DbMethFileRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class _DbMethFile extends TableImpl<_DbMethFileRecord> {

    private static final long serialVersionUID = 700655697;

    /**
     * The reference instance of <code>_db_meth_file</code>
     */
    public static final _DbMethFile _DB_METH_FILE = new _DbMethFile();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<_DbMethFileRecord> getRecordType() {
        return _DbMethFileRecord.class;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public final TableField<_DbMethFileRecord, Object> CLASS_OF = createField("class_of", org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public final TableField<_DbMethFileRecord, Object> FROM_CLASS_OF = createField("from_class_of", org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * The column <code>_db_meth_file.path_name</code>.
     */
    public final TableField<_DbMethFileRecord, String> PATH_NAME = createField("path_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>_db_meth_file</code> table reference
     */
    public _DbMethFile() {
        this(DSL.name("_db_meth_file"), null);
    }

    /**
     * Create an aliased <code>_db_meth_file</code> table reference
     */
    public _DbMethFile(String alias) {
        this(DSL.name(alias), _DB_METH_FILE);
    }

    /**
     * Create an aliased <code>_db_meth_file</code> table reference
     */
    public _DbMethFile(Name alias) {
        this(alias, _DB_METH_FILE);
    }

    private _DbMethFile(Name alias, Table<_DbMethFileRecord> aliased) {
        this(alias, aliased, null);
    }

    private _DbMethFile(Name alias, Table<_DbMethFileRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _DbMethFile as(String alias) {
        return new _DbMethFile(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _DbMethFile as(Name alias) {
        return new _DbMethFile(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public _DbMethFile rename(String name) {
        return new _DbMethFile(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public _DbMethFile rename(Name name) {
        return new _DbMethFile(name, null);
    }
}
