/*
 * This file is generated by jOOQ.
*/
package provendordb.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import provendordb.DefaultSchema;
import provendordb.Keys;
import provendordb.tables.records._DbStoredProcedureRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class _DbStoredProcedure extends TableImpl<_DbStoredProcedureRecord> {

    private static final long serialVersionUID = -1960397883;

    /**
     * The reference instance of <code>_db_stored_procedure</code>
     */
    public static final _DbStoredProcedure _DB_STORED_PROCEDURE = new _DbStoredProcedure();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<_DbStoredProcedureRecord> getRecordType() {
        return _DbStoredProcedureRecord.class;
    }

    /**
     * The column <code>_db_stored_procedure.sp_name</code>.
     */
    public final TableField<_DbStoredProcedureRecord, String> SP_NAME = createField("sp_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>_db_stored_procedure.sp_type</code>.
     */
    public final TableField<_DbStoredProcedureRecord, Integer> SP_TYPE = createField("sp_type", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>_db_stored_procedure.return_type</code>.
     */
    public final TableField<_DbStoredProcedureRecord, Integer> RETURN_TYPE = createField("return_type", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>_db_stored_procedure.arg_count</code>.
     */
    public final TableField<_DbStoredProcedureRecord, Integer> ARG_COUNT = createField("arg_count", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public final TableField<_DbStoredProcedureRecord, Object> ARGS = createField("args", org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * The column <code>_db_stored_procedure.lang</code>.
     */
    public final TableField<_DbStoredProcedureRecord, Integer> LANG = createField("lang", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>_db_stored_procedure.target</code>.
     */
    public final TableField<_DbStoredProcedureRecord, String> TARGET = createField("target", org.jooq.impl.SQLDataType.VARCHAR(4096), this, "");

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public final TableField<_DbStoredProcedureRecord, Object> OWNER = createField("owner", org.jooq.impl.SQLDataType.OTHER, this, "");

    /**
     * The column <code>_db_stored_procedure.comment</code>.
     */
    public final TableField<_DbStoredProcedureRecord, String> COMMENT = createField("comment", org.jooq.impl.SQLDataType.VARCHAR(1024), this, "");

    /**
     * Create a <code>_db_stored_procedure</code> table reference
     */
    public _DbStoredProcedure() {
        this(DSL.name("_db_stored_procedure"), null);
    }

    /**
     * Create an aliased <code>_db_stored_procedure</code> table reference
     */
    public _DbStoredProcedure(String alias) {
        this(DSL.name(alias), _DB_STORED_PROCEDURE);
    }

    /**
     * Create an aliased <code>_db_stored_procedure</code> table reference
     */
    public _DbStoredProcedure(Name alias) {
        this(alias, _DB_STORED_PROCEDURE);
    }

    private _DbStoredProcedure(Name alias, Table<_DbStoredProcedureRecord> aliased) {
        this(alias, aliased, null);
    }

    private _DbStoredProcedure(Name alias, Table<_DbStoredProcedureRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<_DbStoredProcedureRecord>> getKeys() {
        return Arrays.<UniqueKey<_DbStoredProcedureRecord>>asList(Keys._DB_STORED_PROCEDURE__U__DB_STORED_PROCEDURE_SP_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _DbStoredProcedure as(String alias) {
        return new _DbStoredProcedure(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public _DbStoredProcedure as(Name alias) {
        return new _DbStoredProcedure(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public _DbStoredProcedure rename(String name) {
        return new _DbStoredProcedure(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public _DbStoredProcedure rename(Name name) {
        return new _DbStoredProcedure(name, null);
    }
}
