/*
 * This file is generated by jOOQ.
*/
package provendordb.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import provendordb.DefaultSchema;
import provendordb.tables.records.DbAttrSetdomainElmRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbAttrSetdomainElm extends TableImpl<DbAttrSetdomainElmRecord> {

    private static final long serialVersionUID = 962296702;

    /**
     * The reference instance of <code>db_attr_setdomain_elm</code>
     */
    public static final DbAttrSetdomainElm DB_ATTR_SETDOMAIN_ELM = new DbAttrSetdomainElm();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DbAttrSetdomainElmRecord> getRecordType() {
        return DbAttrSetdomainElmRecord.class;
    }

    /**
     * The column <code>db_attr_setdomain_elm.attr_name</code>.
     */
    public final TableField<DbAttrSetdomainElmRecord, String> ATTR_NAME = createField("attr_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>db_attr_setdomain_elm.class_name</code>.
     */
    public final TableField<DbAttrSetdomainElmRecord, String> CLASS_NAME = createField("class_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>db_attr_setdomain_elm.attr_type</code>.
     */
    public final TableField<DbAttrSetdomainElmRecord, String> ATTR_TYPE = createField("attr_type", org.jooq.impl.SQLDataType.VARCHAR(8), this, "");

    /**
     * The column <code>db_attr_setdomain_elm.data_type</code>.
     */
    public final TableField<DbAttrSetdomainElmRecord, String> DATA_TYPE = createField("data_type", org.jooq.impl.SQLDataType.VARCHAR(9), this, "");

    /**
     * The column <code>db_attr_setdomain_elm.prec</code>.
     */
    public final TableField<DbAttrSetdomainElmRecord, Integer> PREC = createField("prec", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>db_attr_setdomain_elm.scale</code>.
     */
    public final TableField<DbAttrSetdomainElmRecord, Integer> SCALE = createField("scale", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>db_attr_setdomain_elm.code_set</code>.
     */
    public final TableField<DbAttrSetdomainElmRecord, Integer> CODE_SET = createField("code_set", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>db_attr_setdomain_elm.domain_class_name</code>.
     */
    public final TableField<DbAttrSetdomainElmRecord, String> DOMAIN_CLASS_NAME = createField("domain_class_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>db_attr_setdomain_elm</code> table reference
     */
    public DbAttrSetdomainElm() {
        this(DSL.name("db_attr_setdomain_elm"), null);
    }

    /**
     * Create an aliased <code>db_attr_setdomain_elm</code> table reference
     */
    public DbAttrSetdomainElm(String alias) {
        this(DSL.name(alias), DB_ATTR_SETDOMAIN_ELM);
    }

    /**
     * Create an aliased <code>db_attr_setdomain_elm</code> table reference
     */
    public DbAttrSetdomainElm(Name alias) {
        this(alias, DB_ATTR_SETDOMAIN_ELM);
    }

    private DbAttrSetdomainElm(Name alias, Table<DbAttrSetdomainElmRecord> aliased) {
        this(alias, aliased, null);
    }

    private DbAttrSetdomainElm(Name alias, Table<DbAttrSetdomainElmRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbAttrSetdomainElm as(String alias) {
        return new DbAttrSetdomainElm(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbAttrSetdomainElm as(Name alias) {
        return new DbAttrSetdomainElm(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DbAttrSetdomainElm rename(String name) {
        return new DbAttrSetdomainElm(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DbAttrSetdomainElm rename(Name name) {
        return new DbAttrSetdomainElm(name, null);
    }
}
