/*
 * This file is generated by jOOQ.
*/
package provendordb.tables;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import provendordb.DefaultSchema;
import provendordb.tables.records.DbMethodRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbMethod extends TableImpl<DbMethodRecord> {

    private static final long serialVersionUID = 492535308;

    /**
     * The reference instance of <code>db_method</code>
     */
    public static final DbMethod DB_METHOD = new DbMethod();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DbMethodRecord> getRecordType() {
        return DbMethodRecord.class;
    }

    /**
     * The column <code>db_method.meth_name</code>.
     */
    public final TableField<DbMethodRecord, String> METH_NAME = createField("meth_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>db_method.class_name</code>.
     */
    public final TableField<DbMethodRecord, String> CLASS_NAME = createField("class_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>db_method.meth_type</code>.
     */
    public final TableField<DbMethodRecord, String> METH_TYPE = createField("meth_type", org.jooq.impl.SQLDataType.VARCHAR(8), this, "");

    /**
     * The column <code>db_method.from_class_name</code>.
     */
    public final TableField<DbMethodRecord, String> FROM_CLASS_NAME = createField("from_class_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>db_method.from_meth_name</code>.
     */
    public final TableField<DbMethodRecord, String> FROM_METH_NAME = createField("from_meth_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>db_method.func_name</code>.
     */
    public final TableField<DbMethodRecord, String> FUNC_NAME = createField("func_name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * Create a <code>db_method</code> table reference
     */
    public DbMethod() {
        this(DSL.name("db_method"), null);
    }

    /**
     * Create an aliased <code>db_method</code> table reference
     */
    public DbMethod(String alias) {
        this(DSL.name(alias), DB_METHOD);
    }

    /**
     * Create an aliased <code>db_method</code> table reference
     */
    public DbMethod(Name alias) {
        this(alias, DB_METHOD);
    }

    private DbMethod(Name alias, Table<DbMethodRecord> aliased) {
        this(alias, aliased, null);
    }

    private DbMethod(Name alias, Table<DbMethodRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbMethod as(String alias) {
        return new DbMethod(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DbMethod as(Name alias) {
        return new DbMethod(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public DbMethod rename(String name) {
        return new DbMethod(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DbMethod rename(Name name) {
        return new DbMethod(name, null);
    }
}
