/*
 * This file is generated by jOOQ.
*/
package provendordb.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import provendordb.DefaultSchema;
import provendordb.Keys;
import provendordb.tables.records.ProvinfoitemgroupRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Provinfoitemgroup extends TableImpl<ProvinfoitemgroupRecord> {

    private static final long serialVersionUID = 1081379120;

    /**
     * The reference instance of <code>provinfoitemgroup</code>
     */
    public static final Provinfoitemgroup PROVINFOITEMGROUP = new Provinfoitemgroup();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProvinfoitemgroupRecord> getRecordType() {
        return ProvinfoitemgroupRecord.class;
    }

    /**
     * The column <code>provinfoitemgroup.provinfoitemgroupid</code>.
     */
    public final TableField<ProvinfoitemgroupRecord, String> PROVINFOITEMGROUPID = createField("provinfoitemgroupid", org.jooq.impl.SQLDataType.VARCHAR(4096).nullable(false), this, "");

    /**
     * The column <code>provinfoitemgroup.provinfoitemgroupname</code>.
     */
    public final TableField<ProvinfoitemgroupRecord, String> PROVINFOITEMGROUPNAME = createField("provinfoitemgroupname", org.jooq.impl.SQLDataType.VARCHAR(4096), this, "");

    /**
     * The column <code>provinfoitemgroup.provinfoitemtypeid</code>.
     */
    public final TableField<ProvinfoitemgroupRecord, String> PROVINFOITEMTYPEID = createField("provinfoitemtypeid", org.jooq.impl.SQLDataType.VARCHAR(4096), this, "");

    /**
     * The column <code>provinfoitemgroup.provinfoitemgroupdesc</code>.
     */
    public final TableField<ProvinfoitemgroupRecord, String> PROVINFOITEMGROUPDESC = createField("provinfoitemgroupdesc", org.jooq.impl.SQLDataType.VARCHAR(4096), this, "");

    /**
     * Create a <code>provinfoitemgroup</code> table reference
     */
    public Provinfoitemgroup() {
        this(DSL.name("provinfoitemgroup"), null);
    }

    /**
     * Create an aliased <code>provinfoitemgroup</code> table reference
     */
    public Provinfoitemgroup(String alias) {
        this(DSL.name(alias), PROVINFOITEMGROUP);
    }

    /**
     * Create an aliased <code>provinfoitemgroup</code> table reference
     */
    public Provinfoitemgroup(Name alias) {
        this(alias, PROVINFOITEMGROUP);
    }

    private Provinfoitemgroup(Name alias, Table<ProvinfoitemgroupRecord> aliased) {
        this(alias, aliased, null);
    }

    private Provinfoitemgroup(Name alias, Table<ProvinfoitemgroupRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ProvinfoitemgroupRecord> getPrimaryKey() {
        return Keys.PROVINFOITEMGROUP__PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ProvinfoitemgroupRecord>> getKeys() {
        return Arrays.<UniqueKey<ProvinfoitemgroupRecord>>asList(Keys.PROVINFOITEMGROUP__PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ProvinfoitemgroupRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ProvinfoitemgroupRecord, ?>>asList(Keys.PROVINFOITEMGROUP__FK_PROVINFOITEMGROUP_PROVINFOITEMTYPEID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Provinfoitemgroup as(String alias) {
        return new Provinfoitemgroup(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Provinfoitemgroup as(Name alias) {
        return new Provinfoitemgroup(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Provinfoitemgroup rename(String name) {
        return new Provinfoitemgroup(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Provinfoitemgroup rename(Name name) {
        return new Provinfoitemgroup(name, null);
    }
}
