/*
 * This file is generated by jOOQ.
*/
package provendordb.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import provendordb.DefaultSchema;
import provendordb.Keys;
import provendordb.tables.records.ProvsalesinvoiceRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Provsalesinvoice extends TableImpl<ProvsalesinvoiceRecord> {

    private static final long serialVersionUID = 1324372058;

    /**
     * The reference instance of <code>provsalesinvoice</code>
     */
    public static final Provsalesinvoice PROVSALESINVOICE = new Provsalesinvoice();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProvsalesinvoiceRecord> getRecordType() {
        return ProvsalesinvoiceRecord.class;
    }

    /**
     * The column <code>provsalesinvoice.provsalesinvoiceid</code>.
     */
    public final TableField<ProvsalesinvoiceRecord, String> PROVSALESINVOICEID = createField("provsalesinvoiceid", org.jooq.impl.SQLDataType.VARCHAR(4096).nullable(false), this, "");

    /**
     * The column <code>provsalesinvoice.provsalespaymenttype</code>.
     */
    public final TableField<ProvsalesinvoiceRecord, String> PROVSALESPAYMENTTYPE = createField("provsalespaymenttype", org.jooq.impl.SQLDataType.VARCHAR(4096), this, "");

    /**
     * The column <code>provsalesinvoice.provaddcharges</code>.
     */
    public final TableField<ProvsalesinvoiceRecord, Integer> PROVADDCHARGES = createField("provaddcharges", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>provsalesinvoice.provshipmentcharges</code>.
     */
    public final TableField<ProvsalesinvoiceRecord, Integer> PROVSHIPMENTCHARGES = createField("provshipmentcharges", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>provsalesinvoice.provsalesordernumber</code>.
     */
    public final TableField<ProvsalesinvoiceRecord, String> PROVSALESORDERNUMBER = createField("provsalesordernumber", org.jooq.impl.SQLDataType.VARCHAR(4096), this, "");

    /**
     * Create a <code>provsalesinvoice</code> table reference
     */
    public Provsalesinvoice() {
        this(DSL.name("provsalesinvoice"), null);
    }

    /**
     * Create an aliased <code>provsalesinvoice</code> table reference
     */
    public Provsalesinvoice(String alias) {
        this(DSL.name(alias), PROVSALESINVOICE);
    }

    /**
     * Create an aliased <code>provsalesinvoice</code> table reference
     */
    public Provsalesinvoice(Name alias) {
        this(alias, PROVSALESINVOICE);
    }

    private Provsalesinvoice(Name alias, Table<ProvsalesinvoiceRecord> aliased) {
        this(alias, aliased, null);
    }

    private Provsalesinvoice(Name alias, Table<ProvsalesinvoiceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ProvsalesinvoiceRecord> getPrimaryKey() {
        return Keys.PROVSALESINVOICE__PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ProvsalesinvoiceRecord>> getKeys() {
        return Arrays.<UniqueKey<ProvsalesinvoiceRecord>>asList(Keys.PROVSALESINVOICE__PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ProvsalesinvoiceRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ProvsalesinvoiceRecord, ?>>asList(Keys.PROVSALESINVOICE__FK_PROVSALESINVOICE_PROVSALESORDERNUMBER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Provsalesinvoice as(String alias) {
        return new Provsalesinvoice(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Provsalesinvoice as(Name alias) {
        return new Provsalesinvoice(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Provsalesinvoice rename(String name) {
        return new Provsalesinvoice(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Provsalesinvoice rename(Name name) {
        return new Provsalesinvoice(name, null);
    }
}
