/*
 * This file is generated by jOOQ.
*/
package provendordb.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

import provendordb.DefaultSchema;
import provendordb.Keys;
import provendordb.tables.records.PvsalesorderitemsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pvsalesorderitems extends TableImpl<PvsalesorderitemsRecord> {

    private static final long serialVersionUID = 1221575896;

    /**
     * The reference instance of <code>pvsalesorderitems</code>
     */
    public static final Pvsalesorderitems PVSALESORDERITEMS = new Pvsalesorderitems();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PvsalesorderitemsRecord> getRecordType() {
        return PvsalesorderitemsRecord.class;
    }

    /**
     * The column <code>pvsalesorderitems.pvsalesordernumber</code>.
     */
    public final TableField<PvsalesorderitemsRecord, String> PVSALESORDERNUMBER = createField("pvsalesordernumber", org.jooq.impl.SQLDataType.VARCHAR(4096), this, "");

    /**
     * The column <code>pvsalesorderitems.pvsalesorderitemid</code>.
     */
    public final TableField<PvsalesorderitemsRecord, String> PVSALESORDERITEMID = createField("pvsalesorderitemid", org.jooq.impl.SQLDataType.VARCHAR(4096), this, "");

    /**
     * The column <code>pvsalesorderitems.pvsalesorderitemquantity</code>.
     */
    public final TableField<PvsalesorderitemsRecord, String> PVSALESORDERITEMQUANTITY = createField("pvsalesorderitemquantity", org.jooq.impl.SQLDataType.VARCHAR(4096), this, "");

    /**
     * The column <code>pvsalesorderitems.pvsalesorderitemprice</code>.
     */
    public final TableField<PvsalesorderitemsRecord, String> PVSALESORDERITEMPRICE = createField("pvsalesorderitemprice", org.jooq.impl.SQLDataType.CHAR(1), this, "");

    /**
     * Create a <code>pvsalesorderitems</code> table reference
     */
    public Pvsalesorderitems() {
        this(DSL.name("pvsalesorderitems"), null);
    }

    /**
     * Create an aliased <code>pvsalesorderitems</code> table reference
     */
    public Pvsalesorderitems(String alias) {
        this(DSL.name(alias), PVSALESORDERITEMS);
    }

    /**
     * Create an aliased <code>pvsalesorderitems</code> table reference
     */
    public Pvsalesorderitems(Name alias) {
        this(alias, PVSALESORDERITEMS);
    }

    private Pvsalesorderitems(Name alias, Table<PvsalesorderitemsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Pvsalesorderitems(Name alias, Table<PvsalesorderitemsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return DefaultSchema.DEFAULT_SCHEMA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PvsalesorderitemsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PvsalesorderitemsRecord, ?>>asList(Keys.PVSALESORDERITEMS__FK_PVSALESORDERITEMS_PVSALESORDERNUMBER, Keys.PVSALESORDERITEMS__FK_PVSALESORDERITEMS_PVSALESORDERITEMID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Pvsalesorderitems as(String alias) {
        return new Pvsalesorderitems(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Pvsalesorderitems as(Name alias) {
        return new Pvsalesorderitems(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Pvsalesorderitems rename(String name) {
        return new Pvsalesorderitems(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Pvsalesorderitems rename(Name name) {
        return new Pvsalesorderitems(name, null);
    }
}
