/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class _DbAuth implements Serializable {

    private static final long serialVersionUID = -1813631139;

    private Object  grantor;
    private Object  grantee;
    private Object  classOf;
    private String  authType;
    private Integer isGrantable;

    public _DbAuth() {}

    public _DbAuth(_DbAuth value) {
        this.grantor = value.grantor;
        this.grantee = value.grantee;
        this.classOf = value.classOf;
        this.authType = value.authType;
        this.isGrantable = value.isGrantable;
    }

    public _DbAuth(
        Object  grantor,
        Object  grantee,
        Object  classOf,
        String  authType,
        Integer isGrantable
    ) {
        this.grantor = grantor;
        this.grantee = grantee;
        this.classOf = classOf;
        this.authType = authType;
        this.isGrantable = isGrantable;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getGrantor() {
        return this.grantor;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setGrantor(Object grantor) {
        this.grantor = grantor;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getGrantee() {
        return this.grantee;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setGrantee(Object grantee) {
        this.grantee = grantee;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getClassOf() {
        return this.classOf;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setClassOf(Object classOf) {
        this.classOf = classOf;
    }

    public String getAuthType() {
        return this.authType;
    }

    public void setAuthType(String authType) {
        this.authType = authType;
    }

    public Integer getIsGrantable() {
        return this.isGrantable;
    }

    public void setIsGrantable(Integer isGrantable) {
        this.isGrantable = isGrantable;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("_DbAuth (");

        sb.append(grantor);
        sb.append(", ").append(grantee);
        sb.append(", ").append(classOf);
        sb.append(", ").append(authType);
        sb.append(", ").append(isGrantable);

        sb.append(")");
        return sb.toString();
    }
}
