/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class _DbClass implements Serializable {

    private static final long serialVersionUID = 986290924;

    private Object  classOf;
    private String  className;
    private Integer classType;
    private Integer isSystemClass;
    private Object  owner;
    private Integer instAttrCount;
    private Integer classAttrCount;
    private Integer sharedAttrCount;
    private Integer instMethCount;
    private Integer classMethCount;
    private Integer collationId;
    private Object  subClasses;
    private Object  superClasses;
    private Object  instAttrs;
    private Object  classAttrs;
    private Object  sharedAttrs;
    private Object  instMeths;
    private Object  classMeths;
    private Object  methFiles;
    private Object  querySpecs;
    private Object  indexes;
    private String  comment;
    private Object  partition;

    public _DbClass() {}

    public _DbClass(_DbClass value) {
        this.classOf = value.classOf;
        this.className = value.className;
        this.classType = value.classType;
        this.isSystemClass = value.isSystemClass;
        this.owner = value.owner;
        this.instAttrCount = value.instAttrCount;
        this.classAttrCount = value.classAttrCount;
        this.sharedAttrCount = value.sharedAttrCount;
        this.instMethCount = value.instMethCount;
        this.classMethCount = value.classMethCount;
        this.collationId = value.collationId;
        this.subClasses = value.subClasses;
        this.superClasses = value.superClasses;
        this.instAttrs = value.instAttrs;
        this.classAttrs = value.classAttrs;
        this.sharedAttrs = value.sharedAttrs;
        this.instMeths = value.instMeths;
        this.classMeths = value.classMeths;
        this.methFiles = value.methFiles;
        this.querySpecs = value.querySpecs;
        this.indexes = value.indexes;
        this.comment = value.comment;
        this.partition = value.partition;
    }

    public _DbClass(
        Object  classOf,
        String  className,
        Integer classType,
        Integer isSystemClass,
        Object  owner,
        Integer instAttrCount,
        Integer classAttrCount,
        Integer sharedAttrCount,
        Integer instMethCount,
        Integer classMethCount,
        Integer collationId,
        Object  subClasses,
        Object  superClasses,
        Object  instAttrs,
        Object  classAttrs,
        Object  sharedAttrs,
        Object  instMeths,
        Object  classMeths,
        Object  methFiles,
        Object  querySpecs,
        Object  indexes,
        String  comment,
        Object  partition
    ) {
        this.classOf = classOf;
        this.className = className;
        this.classType = classType;
        this.isSystemClass = isSystemClass;
        this.owner = owner;
        this.instAttrCount = instAttrCount;
        this.classAttrCount = classAttrCount;
        this.sharedAttrCount = sharedAttrCount;
        this.instMethCount = instMethCount;
        this.classMethCount = classMethCount;
        this.collationId = collationId;
        this.subClasses = subClasses;
        this.superClasses = superClasses;
        this.instAttrs = instAttrs;
        this.classAttrs = classAttrs;
        this.sharedAttrs = sharedAttrs;
        this.instMeths = instMeths;
        this.classMeths = classMeths;
        this.methFiles = methFiles;
        this.querySpecs = querySpecs;
        this.indexes = indexes;
        this.comment = comment;
        this.partition = partition;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getClassOf() {
        return this.classOf;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setClassOf(Object classOf) {
        this.classOf = classOf;
    }

    public String getClassName() {
        return this.className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    public Integer getClassType() {
        return this.classType;
    }

    public void setClassType(Integer classType) {
        this.classType = classType;
    }

    public Integer getIsSystemClass() {
        return this.isSystemClass;
    }

    public void setIsSystemClass(Integer isSystemClass) {
        this.isSystemClass = isSystemClass;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getOwner() {
        return this.owner;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setOwner(Object owner) {
        this.owner = owner;
    }

    public Integer getInstAttrCount() {
        return this.instAttrCount;
    }

    public void setInstAttrCount(Integer instAttrCount) {
        this.instAttrCount = instAttrCount;
    }

    public Integer getClassAttrCount() {
        return this.classAttrCount;
    }

    public void setClassAttrCount(Integer classAttrCount) {
        this.classAttrCount = classAttrCount;
    }

    public Integer getSharedAttrCount() {
        return this.sharedAttrCount;
    }

    public void setSharedAttrCount(Integer sharedAttrCount) {
        this.sharedAttrCount = sharedAttrCount;
    }

    public Integer getInstMethCount() {
        return this.instMethCount;
    }

    public void setInstMethCount(Integer instMethCount) {
        this.instMethCount = instMethCount;
    }

    public Integer getClassMethCount() {
        return this.classMethCount;
    }

    public void setClassMethCount(Integer classMethCount) {
        this.classMethCount = classMethCount;
    }

    public Integer getCollationId() {
        return this.collationId;
    }

    public void setCollationId(Integer collationId) {
        this.collationId = collationId;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getSubClasses() {
        return this.subClasses;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setSubClasses(Object subClasses) {
        this.subClasses = subClasses;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getSuperClasses() {
        return this.superClasses;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setSuperClasses(Object superClasses) {
        this.superClasses = superClasses;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getInstAttrs() {
        return this.instAttrs;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setInstAttrs(Object instAttrs) {
        this.instAttrs = instAttrs;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getClassAttrs() {
        return this.classAttrs;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setClassAttrs(Object classAttrs) {
        this.classAttrs = classAttrs;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getSharedAttrs() {
        return this.sharedAttrs;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setSharedAttrs(Object sharedAttrs) {
        this.sharedAttrs = sharedAttrs;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getInstMeths() {
        return this.instMeths;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setInstMeths(Object instMeths) {
        this.instMeths = instMeths;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getClassMeths() {
        return this.classMeths;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setClassMeths(Object classMeths) {
        this.classMeths = classMeths;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getMethFiles() {
        return this.methFiles;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setMethFiles(Object methFiles) {
        this.methFiles = methFiles;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getQuerySpecs() {
        return this.querySpecs;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setQuerySpecs(Object querySpecs) {
        this.querySpecs = querySpecs;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getIndexes() {
        return this.indexes;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setIndexes(Object indexes) {
        this.indexes = indexes;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getPartition() {
        return this.partition;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setPartition(Object partition) {
        this.partition = partition;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("_DbClass (");

        sb.append(classOf);
        sb.append(", ").append(className);
        sb.append(", ").append(classType);
        sb.append(", ").append(isSystemClass);
        sb.append(", ").append(owner);
        sb.append(", ").append(instAttrCount);
        sb.append(", ").append(classAttrCount);
        sb.append(", ").append(sharedAttrCount);
        sb.append(", ").append(instMethCount);
        sb.append(", ").append(classMethCount);
        sb.append(", ").append(collationId);
        sb.append(", ").append(subClasses);
        sb.append(", ").append(superClasses);
        sb.append(", ").append(instAttrs);
        sb.append(", ").append(classAttrs);
        sb.append(", ").append(sharedAttrs);
        sb.append(", ").append(instMeths);
        sb.append(", ").append(classMeths);
        sb.append(", ").append(methFiles);
        sb.append(", ").append(querySpecs);
        sb.append(", ").append(indexes);
        sb.append(", ").append(comment);
        sb.append(", ").append(partition);

        sb.append(")");
        return sb.toString();
    }
}
