/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class _DbDomain implements Serializable {

    private static final long serialVersionUID = 561567157;

    private Object  objectOf;
    private Integer dataType;
    private Integer prec;
    private Integer scale;
    private Object  classOf;
    private Integer codeSet;
    private Integer collationId;
    private Object  enumeration;
    private Object  setDomains;

    public _DbDomain() {}

    public _DbDomain(_DbDomain value) {
        this.objectOf = value.objectOf;
        this.dataType = value.dataType;
        this.prec = value.prec;
        this.scale = value.scale;
        this.classOf = value.classOf;
        this.codeSet = value.codeSet;
        this.collationId = value.collationId;
        this.enumeration = value.enumeration;
        this.setDomains = value.setDomains;
    }

    public _DbDomain(
        Object  objectOf,
        Integer dataType,
        Integer prec,
        Integer scale,
        Object  classOf,
        Integer codeSet,
        Integer collationId,
        Object  enumeration,
        Object  setDomains
    ) {
        this.objectOf = objectOf;
        this.dataType = dataType;
        this.prec = prec;
        this.scale = scale;
        this.classOf = classOf;
        this.codeSet = codeSet;
        this.collationId = collationId;
        this.enumeration = enumeration;
        this.setDomains = setDomains;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getObjectOf() {
        return this.objectOf;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setObjectOf(Object objectOf) {
        this.objectOf = objectOf;
    }

    public Integer getDataType() {
        return this.dataType;
    }

    public void setDataType(Integer dataType) {
        this.dataType = dataType;
    }

    public Integer getPrec() {
        return this.prec;
    }

    public void setPrec(Integer prec) {
        this.prec = prec;
    }

    public Integer getScale() {
        return this.scale;
    }

    public void setScale(Integer scale) {
        this.scale = scale;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getClassOf() {
        return this.classOf;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setClassOf(Object classOf) {
        this.classOf = classOf;
    }

    public Integer getCodeSet() {
        return this.codeSet;
    }

    public void setCodeSet(Integer codeSet) {
        this.codeSet = codeSet;
    }

    public Integer getCollationId() {
        return this.collationId;
    }

    public void setCollationId(Integer collationId) {
        this.collationId = collationId;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getEnumeration() {
        return this.enumeration;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setEnumeration(Object enumeration) {
        this.enumeration = enumeration;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getSetDomains() {
        return this.setDomains;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setSetDomains(Object setDomains) {
        this.setDomains = setDomains;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("_DbDomain (");

        sb.append(objectOf);
        sb.append(", ").append(dataType);
        sb.append(", ").append(prec);
        sb.append(", ").append(scale);
        sb.append(", ").append(classOf);
        sb.append(", ").append(codeSet);
        sb.append(", ").append(collationId);
        sb.append(", ").append(enumeration);
        sb.append(", ").append(setDomains);

        sb.append(")");
        return sb.toString();
    }
}
