/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbAttrSetdomainElm implements Serializable {

    private static final long serialVersionUID = -1259238103;

    private String  attrName;
    private String  className;
    private String  attrType;
    private String  dataType;
    private Integer prec;
    private Integer scale;
    private Integer codeSet;
    private String  domainClassName;

    public DbAttrSetdomainElm() {}

    public DbAttrSetdomainElm(DbAttrSetdomainElm value) {
        this.attrName = value.attrName;
        this.className = value.className;
        this.attrType = value.attrType;
        this.dataType = value.dataType;
        this.prec = value.prec;
        this.scale = value.scale;
        this.codeSet = value.codeSet;
        this.domainClassName = value.domainClassName;
    }

    public DbAttrSetdomainElm(
        String  attrName,
        String  className,
        String  attrType,
        String  dataType,
        Integer prec,
        Integer scale,
        Integer codeSet,
        String  domainClassName
    ) {
        this.attrName = attrName;
        this.className = className;
        this.attrType = attrType;
        this.dataType = dataType;
        this.prec = prec;
        this.scale = scale;
        this.codeSet = codeSet;
        this.domainClassName = domainClassName;
    }

    public String getAttrName() {
        return this.attrName;
    }

    public void setAttrName(String attrName) {
        this.attrName = attrName;
    }

    public String getClassName() {
        return this.className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    public String getAttrType() {
        return this.attrType;
    }

    public void setAttrType(String attrType) {
        this.attrType = attrType;
    }

    public String getDataType() {
        return this.dataType;
    }

    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    public Integer getPrec() {
        return this.prec;
    }

    public void setPrec(Integer prec) {
        this.prec = prec;
    }

    public Integer getScale() {
        return this.scale;
    }

    public void setScale(Integer scale) {
        this.scale = scale;
    }

    public Integer getCodeSet() {
        return this.codeSet;
    }

    public void setCodeSet(Integer codeSet) {
        this.codeSet = codeSet;
    }

    public String getDomainClassName() {
        return this.domainClassName;
    }

    public void setDomainClassName(String domainClassName) {
        this.domainClassName = domainClassName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DbAttrSetdomainElm (");

        sb.append(attrName);
        sb.append(", ").append(className);
        sb.append(", ").append(attrType);
        sb.append(", ").append(dataType);
        sb.append(", ").append(prec);
        sb.append(", ").append(scale);
        sb.append(", ").append(codeSet);
        sb.append(", ").append(domainClassName);

        sb.append(")");
        return sb.toString();
    }
}
