/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbCharset implements Serializable {

    private static final long serialVersionUID = -1228633986;

    private Integer charsetId;
    private String  charsetName;
    private String  defaultCollation;
    private Integer charSize;

    public DbCharset() {}

    public DbCharset(DbCharset value) {
        this.charsetId = value.charsetId;
        this.charsetName = value.charsetName;
        this.defaultCollation = value.defaultCollation;
        this.charSize = value.charSize;
    }

    public DbCharset(
        Integer charsetId,
        String  charsetName,
        String  defaultCollation,
        Integer charSize
    ) {
        this.charsetId = charsetId;
        this.charsetName = charsetName;
        this.defaultCollation = defaultCollation;
        this.charSize = charSize;
    }

    public Integer getCharsetId() {
        return this.charsetId;
    }

    public void setCharsetId(Integer charsetId) {
        this.charsetId = charsetId;
    }

    public String getCharsetName() {
        return this.charsetName;
    }

    public void setCharsetName(String charsetName) {
        this.charsetName = charsetName;
    }

    public String getDefaultCollation() {
        return this.defaultCollation;
    }

    public void setDefaultCollation(String defaultCollation) {
        this.defaultCollation = defaultCollation;
    }

    public Integer getCharSize() {
        return this.charSize;
    }

    public void setCharSize(Integer charSize) {
        this.charSize = charSize;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DbCharset (");

        sb.append(charsetId);
        sb.append(", ").append(charsetName);
        sb.append(", ").append(defaultCollation);
        sb.append(", ").append(charSize);

        sb.append(")");
        return sb.toString();
    }
}
