/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbClass implements Serializable {

    private static final long serialVersionUID = -1521250112;

    private String className;
    private String ownerName;
    private String classType;
    private String isSystemClass;
    private String partitioned;
    private String isReuseOidClass;
    private String collation;
    private String comment;

    public DbClass() {}

    public DbClass(DbClass value) {
        this.className = value.className;
        this.ownerName = value.ownerName;
        this.classType = value.classType;
        this.isSystemClass = value.isSystemClass;
        this.partitioned = value.partitioned;
        this.isReuseOidClass = value.isReuseOidClass;
        this.collation = value.collation;
        this.comment = value.comment;
    }

    public DbClass(
        String className,
        String ownerName,
        String classType,
        String isSystemClass,
        String partitioned,
        String isReuseOidClass,
        String collation,
        String comment
    ) {
        this.className = className;
        this.ownerName = ownerName;
        this.classType = classType;
        this.isSystemClass = isSystemClass;
        this.partitioned = partitioned;
        this.isReuseOidClass = isReuseOidClass;
        this.collation = collation;
        this.comment = comment;
    }

    public String getClassName() {
        return this.className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    public String getOwnerName() {
        return this.ownerName;
    }

    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }

    public String getClassType() {
        return this.classType;
    }

    public void setClassType(String classType) {
        this.classType = classType;
    }

    public String getIsSystemClass() {
        return this.isSystemClass;
    }

    public void setIsSystemClass(String isSystemClass) {
        this.isSystemClass = isSystemClass;
    }

    public String getPartitioned() {
        return this.partitioned;
    }

    public void setPartitioned(String partitioned) {
        this.partitioned = partitioned;
    }

    public String getIsReuseOidClass() {
        return this.isReuseOidClass;
    }

    public void setIsReuseOidClass(String isReuseOidClass) {
        this.isReuseOidClass = isReuseOidClass;
    }

    public String getCollation() {
        return this.collation;
    }

    public void setCollation(String collation) {
        this.collation = collation;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DbClass (");

        sb.append(className);
        sb.append(", ").append(ownerName);
        sb.append(", ").append(classType);
        sb.append(", ").append(isSystemClass);
        sb.append(", ").append(partitioned);
        sb.append(", ").append(isReuseOidClass);
        sb.append(", ").append(collation);
        sb.append(", ").append(comment);

        sb.append(")");
        return sb.toString();
    }
}
