/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbIndex implements Serializable {

    private static final long serialVersionUID = -334605973;

    private String  indexName;
    private String  isUnique;
    private String  isReverse;
    private String  className;
    private Integer keyCount;
    private String  isPrimaryKey;
    private String  isForeignKey;
    private String  filterExpression;
    private String  haveFunction;
    private String  comment;

    public DbIndex() {}

    public DbIndex(DbIndex value) {
        this.indexName = value.indexName;
        this.isUnique = value.isUnique;
        this.isReverse = value.isReverse;
        this.className = value.className;
        this.keyCount = value.keyCount;
        this.isPrimaryKey = value.isPrimaryKey;
        this.isForeignKey = value.isForeignKey;
        this.filterExpression = value.filterExpression;
        this.haveFunction = value.haveFunction;
        this.comment = value.comment;
    }

    public DbIndex(
        String  indexName,
        String  isUnique,
        String  isReverse,
        String  className,
        Integer keyCount,
        String  isPrimaryKey,
        String  isForeignKey,
        String  filterExpression,
        String  haveFunction,
        String  comment
    ) {
        this.indexName = indexName;
        this.isUnique = isUnique;
        this.isReverse = isReverse;
        this.className = className;
        this.keyCount = keyCount;
        this.isPrimaryKey = isPrimaryKey;
        this.isForeignKey = isForeignKey;
        this.filterExpression = filterExpression;
        this.haveFunction = haveFunction;
        this.comment = comment;
    }

    public String getIndexName() {
        return this.indexName;
    }

    public void setIndexName(String indexName) {
        this.indexName = indexName;
    }

    public String getIsUnique() {
        return this.isUnique;
    }

    public void setIsUnique(String isUnique) {
        this.isUnique = isUnique;
    }

    public String getIsReverse() {
        return this.isReverse;
    }

    public void setIsReverse(String isReverse) {
        this.isReverse = isReverse;
    }

    public String getClassName() {
        return this.className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    public Integer getKeyCount() {
        return this.keyCount;
    }

    public void setKeyCount(Integer keyCount) {
        this.keyCount = keyCount;
    }

    public String getIsPrimaryKey() {
        return this.isPrimaryKey;
    }

    public void setIsPrimaryKey(String isPrimaryKey) {
        this.isPrimaryKey = isPrimaryKey;
    }

    public String getIsForeignKey() {
        return this.isForeignKey;
    }

    public void setIsForeignKey(String isForeignKey) {
        this.isForeignKey = isForeignKey;
    }

    public String getFilterExpression() {
        return this.filterExpression;
    }

    public void setFilterExpression(String filterExpression) {
        this.filterExpression = filterExpression;
    }

    public String getHaveFunction() {
        return this.haveFunction;
    }

    public void setHaveFunction(String haveFunction) {
        this.haveFunction = haveFunction;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DbIndex (");

        sb.append(indexName);
        sb.append(", ").append(isUnique);
        sb.append(", ").append(isReverse);
        sb.append(", ").append(className);
        sb.append(", ").append(keyCount);
        sb.append(", ").append(isPrimaryKey);
        sb.append(", ").append(isForeignKey);
        sb.append(", ").append(filterExpression);
        sb.append(", ").append(haveFunction);
        sb.append(", ").append(comment);

        sb.append(")");
        return sb.toString();
    }
}
