/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbIndexKey implements Serializable {

    private static final long serialVersionUID = 1813864402;

    private String  indexName;
    private String  className;
    private String  keyAttrName;
    private Integer keyOrder;
    private String  ascDesc;
    private Integer keyPrefixLength;
    private String  func;

    public DbIndexKey() {}

    public DbIndexKey(DbIndexKey value) {
        this.indexName = value.indexName;
        this.className = value.className;
        this.keyAttrName = value.keyAttrName;
        this.keyOrder = value.keyOrder;
        this.ascDesc = value.ascDesc;
        this.keyPrefixLength = value.keyPrefixLength;
        this.func = value.func;
    }

    public DbIndexKey(
        String  indexName,
        String  className,
        String  keyAttrName,
        Integer keyOrder,
        String  ascDesc,
        Integer keyPrefixLength,
        String  func
    ) {
        this.indexName = indexName;
        this.className = className;
        this.keyAttrName = keyAttrName;
        this.keyOrder = keyOrder;
        this.ascDesc = ascDesc;
        this.keyPrefixLength = keyPrefixLength;
        this.func = func;
    }

    public String getIndexName() {
        return this.indexName;
    }

    public void setIndexName(String indexName) {
        this.indexName = indexName;
    }

    public String getClassName() {
        return this.className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    public String getKeyAttrName() {
        return this.keyAttrName;
    }

    public void setKeyAttrName(String keyAttrName) {
        this.keyAttrName = keyAttrName;
    }

    public Integer getKeyOrder() {
        return this.keyOrder;
    }

    public void setKeyOrder(Integer keyOrder) {
        this.keyOrder = keyOrder;
    }

    public String getAscDesc() {
        return this.ascDesc;
    }

    public void setAscDesc(String ascDesc) {
        this.ascDesc = ascDesc;
    }

    public Integer getKeyPrefixLength() {
        return this.keyPrefixLength;
    }

    public void setKeyPrefixLength(Integer keyPrefixLength) {
        this.keyPrefixLength = keyPrefixLength;
    }

    public String getFunc() {
        return this.func;
    }

    public void setFunc(String func) {
        this.func = func;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DbIndexKey (");

        sb.append(indexName);
        sb.append(", ").append(className);
        sb.append(", ").append(keyAttrName);
        sb.append(", ").append(keyOrder);
        sb.append(", ").append(ascDesc);
        sb.append(", ").append(keyPrefixLength);
        sb.append(", ").append(func);

        sb.append(")");
        return sb.toString();
    }
}
