/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbMethFile implements Serializable {

    private static final long serialVersionUID = 630354087;

    private String className;
    private String pathName;
    private String fromClassName;

    public DbMethFile() {}

    public DbMethFile(DbMethFile value) {
        this.className = value.className;
        this.pathName = value.pathName;
        this.fromClassName = value.fromClassName;
    }

    public DbMethFile(
        String className,
        String pathName,
        String fromClassName
    ) {
        this.className = className;
        this.pathName = pathName;
        this.fromClassName = fromClassName;
    }

    public String getClassName() {
        return this.className;
    }

    public void setClassName(String className) {
        this.className = className;
    }

    public String getPathName() {
        return this.pathName;
    }

    public void setPathName(String pathName) {
        this.pathName = pathName;
    }

    public String getFromClassName() {
        return this.fromClassName;
    }

    public void setFromClassName(String fromClassName) {
        this.fromClassName = fromClassName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DbMethFile (");

        sb.append(className);
        sb.append(", ").append(pathName);
        sb.append(", ").append(fromClassName);

        sb.append(")");
        return sb.toString();
    }
}
