/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbStoredProcedureArgs implements Serializable {

    private static final long serialVersionUID = -343756371;

    private String  spName;
    private Integer indexOf;
    private String  argName;
    private String  dataType;
    private String  mode;
    private String  comment;

    public DbStoredProcedureArgs() {}

    public DbStoredProcedureArgs(DbStoredProcedureArgs value) {
        this.spName = value.spName;
        this.indexOf = value.indexOf;
        this.argName = value.argName;
        this.dataType = value.dataType;
        this.mode = value.mode;
        this.comment = value.comment;
    }

    public DbStoredProcedureArgs(
        String  spName,
        Integer indexOf,
        String  argName,
        String  dataType,
        String  mode,
        String  comment
    ) {
        this.spName = spName;
        this.indexOf = indexOf;
        this.argName = argName;
        this.dataType = dataType;
        this.mode = mode;
        this.comment = comment;
    }

    public String getSpName() {
        return this.spName;
    }

    public void setSpName(String spName) {
        this.spName = spName;
    }

    public Integer getIndexOf() {
        return this.indexOf;
    }

    public void setIndexOf(Integer indexOf) {
        this.indexOf = indexOf;
    }

    public String getArgName() {
        return this.argName;
    }

    public void setArgName(String argName) {
        this.argName = argName;
    }

    public String getDataType() {
        return this.dataType;
    }

    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    public String getMode() {
        return this.mode;
    }

    public void setMode(String mode) {
        this.mode = mode;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DbStoredProcedureArgs (");

        sb.append(spName);
        sb.append(", ").append(indexOf);
        sb.append(", ").append(argName);
        sb.append(", ").append(dataType);
        sb.append(", ").append(mode);
        sb.append(", ").append(comment);

        sb.append(")");
        return sb.toString();
    }
}
