/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbStoredProcedure implements Serializable {

    private static final long serialVersionUID = 887165496;

    private String  spName;
    private String  spType;
    private String  returnType;
    private Integer argCount;
    private String  lang;
    private String  target;
    private String  owner;
    private String  comment;

    public DbStoredProcedure() {}

    public DbStoredProcedure(DbStoredProcedure value) {
        this.spName = value.spName;
        this.spType = value.spType;
        this.returnType = value.returnType;
        this.argCount = value.argCount;
        this.lang = value.lang;
        this.target = value.target;
        this.owner = value.owner;
        this.comment = value.comment;
    }

    public DbStoredProcedure(
        String  spName,
        String  spType,
        String  returnType,
        Integer argCount,
        String  lang,
        String  target,
        String  owner,
        String  comment
    ) {
        this.spName = spName;
        this.spType = spType;
        this.returnType = returnType;
        this.argCount = argCount;
        this.lang = lang;
        this.target = target;
        this.owner = owner;
        this.comment = comment;
    }

    public String getSpName() {
        return this.spName;
    }

    public void setSpName(String spName) {
        this.spName = spName;
    }

    public String getSpType() {
        return this.spType;
    }

    public void setSpType(String spType) {
        this.spType = spType;
    }

    public String getReturnType() {
        return this.returnType;
    }

    public void setReturnType(String returnType) {
        this.returnType = returnType;
    }

    public Integer getArgCount() {
        return this.argCount;
    }

    public void setArgCount(Integer argCount) {
        this.argCount = argCount;
    }

    public String getLang() {
        return this.lang;
    }

    public void setLang(String lang) {
        this.lang = lang;
    }

    public String getTarget() {
        return this.target;
    }

    public void setTarget(String target) {
        this.target = target;
    }

    public String getOwner() {
        return this.owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DbStoredProcedure (");

        sb.append(spName);
        sb.append(", ").append(spType);
        sb.append(", ").append(returnType);
        sb.append(", ").append(argCount);
        sb.append(", ").append(lang);
        sb.append(", ").append(target);
        sb.append(", ").append(owner);
        sb.append(", ").append(comment);

        sb.append(")");
        return sb.toString();
    }
}
