/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbTrigger implements Serializable {

    private static final long serialVersionUID = -1268358561;

    private Object  owner;
    private String  name;
    private Integer status;
    private Double  priority;
    private Integer event;
    private Object  targetClass;
    private String  targetAttribute;
    private Integer targetClassAttribute;
    private Integer conditionType;
    private String  condition;
    private Integer conditionTime;
    private Integer actionType;
    private String  actionDefinition;
    private Integer actionTime;
    private String  comment;

    public DbTrigger() {}

    public DbTrigger(DbTrigger value) {
        this.owner = value.owner;
        this.name = value.name;
        this.status = value.status;
        this.priority = value.priority;
        this.event = value.event;
        this.targetClass = value.targetClass;
        this.targetAttribute = value.targetAttribute;
        this.targetClassAttribute = value.targetClassAttribute;
        this.conditionType = value.conditionType;
        this.condition = value.condition;
        this.conditionTime = value.conditionTime;
        this.actionType = value.actionType;
        this.actionDefinition = value.actionDefinition;
        this.actionTime = value.actionTime;
        this.comment = value.comment;
    }

    public DbTrigger(
        Object  owner,
        String  name,
        Integer status,
        Double  priority,
        Integer event,
        Object  targetClass,
        String  targetAttribute,
        Integer targetClassAttribute,
        Integer conditionType,
        String  condition,
        Integer conditionTime,
        Integer actionType,
        String  actionDefinition,
        Integer actionTime,
        String  comment
    ) {
        this.owner = owner;
        this.name = name;
        this.status = status;
        this.priority = priority;
        this.event = event;
        this.targetClass = targetClass;
        this.targetAttribute = targetAttribute;
        this.targetClassAttribute = targetClassAttribute;
        this.conditionType = conditionType;
        this.condition = condition;
        this.conditionTime = conditionTime;
        this.actionType = actionType;
        this.actionDefinition = actionDefinition;
        this.actionTime = actionTime;
        this.comment = comment;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getOwner() {
        return this.owner;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setOwner(Object owner) {
        this.owner = owner;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getStatus() {
        return this.status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public Double getPriority() {
        return this.priority;
    }

    public void setPriority(Double priority) {
        this.priority = priority;
    }

    public Integer getEvent() {
        return this.event;
    }

    public void setEvent(Integer event) {
        this.event = event;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getTargetClass() {
        return this.targetClass;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setTargetClass(Object targetClass) {
        this.targetClass = targetClass;
    }

    public String getTargetAttribute() {
        return this.targetAttribute;
    }

    public void setTargetAttribute(String targetAttribute) {
        this.targetAttribute = targetAttribute;
    }

    public Integer getTargetClassAttribute() {
        return this.targetClassAttribute;
    }

    public void setTargetClassAttribute(Integer targetClassAttribute) {
        this.targetClassAttribute = targetClassAttribute;
    }

    public Integer getConditionType() {
        return this.conditionType;
    }

    public void setConditionType(Integer conditionType) {
        this.conditionType = conditionType;
    }

    public String getCondition() {
        return this.condition;
    }

    public void setCondition(String condition) {
        this.condition = condition;
    }

    public Integer getConditionTime() {
        return this.conditionTime;
    }

    public void setConditionTime(Integer conditionTime) {
        this.conditionTime = conditionTime;
    }

    public Integer getActionType() {
        return this.actionType;
    }

    public void setActionType(Integer actionType) {
        this.actionType = actionType;
    }

    public String getActionDefinition() {
        return this.actionDefinition;
    }

    public void setActionDefinition(String actionDefinition) {
        this.actionDefinition = actionDefinition;
    }

    public Integer getActionTime() {
        return this.actionTime;
    }

    public void setActionTime(Integer actionTime) {
        this.actionTime = actionTime;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DbTrigger (");

        sb.append(owner);
        sb.append(", ").append(name);
        sb.append(", ").append(status);
        sb.append(", ").append(priority);
        sb.append(", ").append(event);
        sb.append(", ").append(targetClass);
        sb.append(", ").append(targetAttribute);
        sb.append(", ").append(targetClassAttribute);
        sb.append(", ").append(conditionType);
        sb.append(", ").append(condition);
        sb.append(", ").append(conditionTime);
        sb.append(", ").append(actionType);
        sb.append(", ").append(actionDefinition);
        sb.append(", ").append(actionTime);
        sb.append(", ").append(comment);

        sb.append(")");
        return sb.toString();
    }
}
