/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DbTrig implements Serializable {

    private static final long serialVersionUID = 1551321057;

    private String  triggerName;
    private String  targetClassName;
    private String  targetAttrName;
    private String  targetAttrType;
    private Integer actionType;
    private Integer actionTime;
    private String  comment;

    public DbTrig() {}

    public DbTrig(DbTrig value) {
        this.triggerName = value.triggerName;
        this.targetClassName = value.targetClassName;
        this.targetAttrName = value.targetAttrName;
        this.targetAttrType = value.targetAttrType;
        this.actionType = value.actionType;
        this.actionTime = value.actionTime;
        this.comment = value.comment;
    }

    public DbTrig(
        String  triggerName,
        String  targetClassName,
        String  targetAttrName,
        String  targetAttrType,
        Integer actionType,
        Integer actionTime,
        String  comment
    ) {
        this.triggerName = triggerName;
        this.targetClassName = targetClassName;
        this.targetAttrName = targetAttrName;
        this.targetAttrType = targetAttrType;
        this.actionType = actionType;
        this.actionTime = actionTime;
        this.comment = comment;
    }

    public String getTriggerName() {
        return this.triggerName;
    }

    public void setTriggerName(String triggerName) {
        this.triggerName = triggerName;
    }

    public String getTargetClassName() {
        return this.targetClassName;
    }

    public void setTargetClassName(String targetClassName) {
        this.targetClassName = targetClassName;
    }

    public String getTargetAttrName() {
        return this.targetAttrName;
    }

    public void setTargetAttrName(String targetAttrName) {
        this.targetAttrName = targetAttrName;
    }

    public String getTargetAttrType() {
        return this.targetAttrType;
    }

    public void setTargetAttrType(String targetAttrType) {
        this.targetAttrType = targetAttrType;
    }

    public Integer getActionType() {
        return this.actionType;
    }

    public void setActionType(Integer actionType) {
        this.actionType = actionType;
    }

    public Integer getActionTime() {
        return this.actionTime;
    }

    public void setActionTime(Integer actionTime) {
        this.actionTime = actionTime;
    }

    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DbTrig (");

        sb.append(triggerName);
        sb.append(", ").append(targetClassName);
        sb.append(", ").append(targetAttrName);
        sb.append(", ").append(targetAttrType);
        sb.append(", ").append(actionType);
        sb.append(", ").append(actionTime);
        sb.append(", ").append(comment);

        sb.append(")");
        return sb.toString();
    }
}
