/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Provinfoitem implements Serializable {

    private static final long serialVersionUID = -968285094;

    private String provinfoitemid;
    private String provinfoitemname;
    private String provinfoitemdesc;
    private String provinfoitemquantity;
    private String provinfoitemexpiry;

    public Provinfoitem() {}

    public Provinfoitem(Provinfoitem value) {
        this.provinfoitemid = value.provinfoitemid;
        this.provinfoitemname = value.provinfoitemname;
        this.provinfoitemdesc = value.provinfoitemdesc;
        this.provinfoitemquantity = value.provinfoitemquantity;
        this.provinfoitemexpiry = value.provinfoitemexpiry;
    }

    public Provinfoitem(
        String provinfoitemid,
        String provinfoitemname,
        String provinfoitemdesc,
        String provinfoitemquantity,
        String provinfoitemexpiry
    ) {
        this.provinfoitemid = provinfoitemid;
        this.provinfoitemname = provinfoitemname;
        this.provinfoitemdesc = provinfoitemdesc;
        this.provinfoitemquantity = provinfoitemquantity;
        this.provinfoitemexpiry = provinfoitemexpiry;
    }

    public String getProvinfoitemid() {
        return this.provinfoitemid;
    }

    public void setProvinfoitemid(String provinfoitemid) {
        this.provinfoitemid = provinfoitemid;
    }

    public String getProvinfoitemname() {
        return this.provinfoitemname;
    }

    public void setProvinfoitemname(String provinfoitemname) {
        this.provinfoitemname = provinfoitemname;
    }

    public String getProvinfoitemdesc() {
        return this.provinfoitemdesc;
    }

    public void setProvinfoitemdesc(String provinfoitemdesc) {
        this.provinfoitemdesc = provinfoitemdesc;
    }

    public String getProvinfoitemquantity() {
        return this.provinfoitemquantity;
    }

    public void setProvinfoitemquantity(String provinfoitemquantity) {
        this.provinfoitemquantity = provinfoitemquantity;
    }

    public String getProvinfoitemexpiry() {
        return this.provinfoitemexpiry;
    }

    public void setProvinfoitemexpiry(String provinfoitemexpiry) {
        this.provinfoitemexpiry = provinfoitemexpiry;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Provinfoitem (");

        sb.append(provinfoitemid);
        sb.append(", ").append(provinfoitemname);
        sb.append(", ").append(provinfoitemdesc);
        sb.append(", ").append(provinfoitemquantity);
        sb.append(", ").append(provinfoitemexpiry);

        sb.append(")");
        return sb.toString();
    }
}
