/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Pvsalesorderitems implements Serializable {

    private static final long serialVersionUID = 1493819692;

    private String pvsalesordernumber;
    private String pvsalesorderitemid;
    private String pvsalesorderitemquantity;
    private String pvsalesorderitemprice;

    public Pvsalesorderitems() {}

    public Pvsalesorderitems(Pvsalesorderitems value) {
        this.pvsalesordernumber = value.pvsalesordernumber;
        this.pvsalesorderitemid = value.pvsalesorderitemid;
        this.pvsalesorderitemquantity = value.pvsalesorderitemquantity;
        this.pvsalesorderitemprice = value.pvsalesorderitemprice;
    }

    public Pvsalesorderitems(
        String pvsalesordernumber,
        String pvsalesorderitemid,
        String pvsalesorderitemquantity,
        String pvsalesorderitemprice
    ) {
        this.pvsalesordernumber = pvsalesordernumber;
        this.pvsalesorderitemid = pvsalesorderitemid;
        this.pvsalesorderitemquantity = pvsalesorderitemquantity;
        this.pvsalesorderitemprice = pvsalesorderitemprice;
    }

    public String getPvsalesordernumber() {
        return this.pvsalesordernumber;
    }

    public void setPvsalesordernumber(String pvsalesordernumber) {
        this.pvsalesordernumber = pvsalesordernumber;
    }

    public String getPvsalesorderitemid() {
        return this.pvsalesorderitemid;
    }

    public void setPvsalesorderitemid(String pvsalesorderitemid) {
        this.pvsalesorderitemid = pvsalesorderitemid;
    }

    public String getPvsalesorderitemquantity() {
        return this.pvsalesorderitemquantity;
    }

    public void setPvsalesorderitemquantity(String pvsalesorderitemquantity) {
        this.pvsalesorderitemquantity = pvsalesorderitemquantity;
    }

    public String getPvsalesorderitemprice() {
        return this.pvsalesorderitemprice;
    }

    public void setPvsalesorderitemprice(String pvsalesorderitemprice) {
        this.pvsalesorderitemprice = pvsalesorderitemprice;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Pvsalesorderitems (");

        sb.append(pvsalesordernumber);
        sb.append(", ").append(pvsalesorderitemid);
        sb.append(", ").append(pvsalesorderitemquantity);
        sb.append(", ").append(pvsalesorderitemprice);

        sb.append(")");
        return sb.toString();
    }
}
