/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;

import provendordb.tables.Provitem;
import provendordb.tables.records.ProvitemRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProvitemDao extends DAOImpl<ProvitemRecord, provendordb.tables.pojos.Provitem, Record2<Integer, String>> {

    /**
     * Create a new ProvitemDao without any configuration
     */
    public ProvitemDao() {
        super(Provitem.PROVITEM, provendordb.tables.pojos.Provitem.class);
    }

    /**
     * Create a new ProvitemDao with an attached configuration
     */
    public ProvitemDao(Configuration configuration) {
        super(Provitem.PROVITEM, provendordb.tables.pojos.Provitem.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<Integer, String> getId(provendordb.tables.pojos.Provitem object) {
        return compositeKeyRecord(object.getProvitemid(), object.getProvitemnumber());
    }

    /**
     * Fetch records that have <code>provitemid IN (values)</code>
     */
    public List<provendordb.tables.pojos.Provitem> fetchByProvitemid(Integer... values) {
        return fetch(Provitem.PROVITEM.PROVITEMID, values);
    }

    /**
     * Fetch records that have <code>provitemnumber IN (values)</code>
     */
    public List<provendordb.tables.pojos.Provitem> fetchByProvitemnumber(String... values) {
        return fetch(Provitem.PROVITEM.PROVITEMNUMBER, values);
    }

    /**
     * Fetch records that have <code>provitemname IN (values)</code>
     */
    public List<provendordb.tables.pojos.Provitem> fetchByProvitemname(String... values) {
        return fetch(Provitem.PROVITEM.PROVITEMNAME, values);
    }

    /**
     * Fetch records that have <code>provitemdescription IN (values)</code>
     */
    public List<provendordb.tables.pojos.Provitem> fetchByProvitemdescription(String... values) {
        return fetch(Provitem.PROVITEM.PROVITEMDESCRIPTION, values);
    }

    /**
     * Fetch records that have <code>provitemtypeid IN (values)</code>
     */
    public List<provendordb.tables.pojos.Provitem> fetchByProvitemtypeid(String... values) {
        return fetch(Provitem.PROVITEM.PROVITEMTYPEID, values);
    }

    /**
     * Fetch records that have <code>provitemgroupid IN (values)</code>
     */
    public List<provendordb.tables.pojos.Provitem> fetchByProvitemgroupid(String... values) {
        return fetch(Provitem.PROVITEM.PROVITEMGROUPID, values);
    }

    /**
     * Fetch records that have <code>provitemfarmerid IN (values)</code>
     */
    public List<provendordb.tables.pojos.Provitem> fetchByProvitemfarmerid(String... values) {
        return fetch(Provitem.PROVITEM.PROVITEMFARMERID, values);
    }

    /**
     * Fetch records that have <code>provitemquantity IN (values)</code>
     */
    public List<provendordb.tables.pojos.Provitem> fetchByProvitemquantity(String... values) {
        return fetch(Provitem.PROVITEM.PROVITEMQUANTITY, values);
    }

    /**
     * Fetch records that have <code>provitemminprice IN (values)</code>
     */
    public List<provendordb.tables.pojos.Provitem> fetchByProvitemminprice(Integer... values) {
        return fetch(Provitem.PROVITEM.PROVITEMMINPRICE, values);
    }

    /**
     * Fetch records that have <code>provitemmaxprice IN (values)</code>
     */
    public List<provendordb.tables.pojos.Provitem> fetchByProvitemmaxprice(Integer... values) {
        return fetch(Provitem.PROVITEM.PROVITEMMAXPRICE, values);
    }

    /**
     * Fetch records that have <code>provitemdeals IN (values)</code>
     */
    public List<provendordb.tables.pojos.Provitem> fetchByProvitemdeals(String... values) {
        return fetch(Provitem.PROVITEM.PROVITEMDEALS, values);
    }
}
