/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import provendordb.tables.Provinfoitemgroup;
import provendordb.tables.records.ProvinfoitemgroupRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProvinfoitemgroupDao extends DAOImpl<ProvinfoitemgroupRecord, provendordb.tables.pojos.Provinfoitemgroup, String> {

    /**
     * Create a new ProvinfoitemgroupDao without any configuration
     */
    public ProvinfoitemgroupDao() {
        super(Provinfoitemgroup.PROVINFOITEMGROUP, provendordb.tables.pojos.Provinfoitemgroup.class);
    }

    /**
     * Create a new ProvinfoitemgroupDao with an attached configuration
     */
    public ProvinfoitemgroupDao(Configuration configuration) {
        super(Provinfoitemgroup.PROVINFOITEMGROUP, provendordb.tables.pojos.Provinfoitemgroup.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(provendordb.tables.pojos.Provinfoitemgroup object) {
        return object.getProvinfoitemgroupid();
    }

    /**
     * Fetch records that have <code>provinfoitemgroupid IN (values)</code>
     */
    public List<provendordb.tables.pojos.Provinfoitemgroup> fetchByProvinfoitemgroupid(String... values) {
        return fetch(Provinfoitemgroup.PROVINFOITEMGROUP.PROVINFOITEMGROUPID, values);
    }

    /**
     * Fetch a unique record that has <code>provinfoitemgroupid = value</code>
     */
    public provendordb.tables.pojos.Provinfoitemgroup fetchOneByProvinfoitemgroupid(String value) {
        return fetchOne(Provinfoitemgroup.PROVINFOITEMGROUP.PROVINFOITEMGROUPID, value);
    }

    /**
     * Fetch records that have <code>provinfoitemgroupname IN (values)</code>
     */
    public List<provendordb.tables.pojos.Provinfoitemgroup> fetchByProvinfoitemgroupname(String... values) {
        return fetch(Provinfoitemgroup.PROVINFOITEMGROUP.PROVINFOITEMGROUPNAME, values);
    }

    /**
     * Fetch records that have <code>provinfoitemtypeid IN (values)</code>
     */
    public List<provendordb.tables.pojos.Provinfoitemgroup> fetchByProvinfoitemtypeid(String... values) {
        return fetch(Provinfoitemgroup.PROVINFOITEMGROUP.PROVINFOITEMTYPEID, values);
    }

    /**
     * Fetch records that have <code>provinfoitemgroupdesc IN (values)</code>
     */
    public List<provendordb.tables.pojos.Provinfoitemgroup> fetchByProvinfoitemgroupdesc(String... values) {
        return fetch(Provinfoitemgroup.PROVINFOITEMGROUP.PROVINFOITEMGROUPDESC, values);
    }
}
