/*
 * This file is generated by jOOQ.
*/
package provendordb.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import provendordb.tables.Provinfoitemtype;
import provendordb.tables.records.ProvinfoitemtypeRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProvinfoitemtypeDao extends DAOImpl<ProvinfoitemtypeRecord, provendordb.tables.pojos.Provinfoitemtype, String> {

    /**
     * Create a new ProvinfoitemtypeDao without any configuration
     */
    public ProvinfoitemtypeDao() {
        super(Provinfoitemtype.PROVINFOITEMTYPE, provendordb.tables.pojos.Provinfoitemtype.class);
    }

    /**
     * Create a new ProvinfoitemtypeDao with an attached configuration
     */
    public ProvinfoitemtypeDao(Configuration configuration) {
        super(Provinfoitemtype.PROVINFOITEMTYPE, provendordb.tables.pojos.Provinfoitemtype.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(provendordb.tables.pojos.Provinfoitemtype object) {
        return object.getProvinfoitemtypeid();
    }

    /**
     * Fetch records that have <code>provinfoitemtypeid IN (values)</code>
     */
    public List<provendordb.tables.pojos.Provinfoitemtype> fetchByProvinfoitemtypeid(String... values) {
        return fetch(Provinfoitemtype.PROVINFOITEMTYPE.PROVINFOITEMTYPEID, values);
    }

    /**
     * Fetch a unique record that has <code>provinfoitemtypeid = value</code>
     */
    public provendordb.tables.pojos.Provinfoitemtype fetchOneByProvinfoitemtypeid(String value) {
        return fetchOne(Provinfoitemtype.PROVINFOITEMTYPE.PROVINFOITEMTYPEID, value);
    }

    /**
     * Fetch records that have <code>provinfoitemtypename IN (values)</code>
     */
    public List<provendordb.tables.pojos.Provinfoitemtype> fetchByProvinfoitemtypename(String... values) {
        return fetch(Provinfoitemtype.PROVINFOITEMTYPE.PROVINFOITEMTYPENAME, values);
    }

    /**
     * Fetch records that have <code>provinfoitemtypedesc IN (values)</code>
     */
    public List<provendordb.tables.pojos.Provinfoitemtype> fetchByProvinfoitemtypedesc(String... values) {
        return fetch(Provinfoitemtype.PROVINFOITEMTYPE.PROVINFOITEMTYPEDESC, values);
    }

    /**
     * Fetch records that have <code>provinfoitemid IN (values)</code>
     */
    public List<provendordb.tables.pojos.Provinfoitemtype> fetchByProvinfoitemid(String... values) {
        return fetch(Provinfoitemtype.PROVINFOITEMTYPE.PROVINFOITEMID, values);
    }
}
